# Generated by Django 6.1 on 2026-08-23 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto', models.CharField(max_length=10)),
                ('id_externo', models.CharField(max_length=100)),
                ('app', models.CharField(blank=True, max_length=20)),
                ('razon_social', models.CharField(max_length=255)),
                ('nombre_comercial', models.CharField(blank=True, max_length=255)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva'), ('baja_erp', 'Baja en ERP')], default='activa', max_length=20)),
                ('ultima_sync', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['razon_social'],
                'constraints': [models.UniqueConstraint(fields=('proyecto', 'id_externo'), name='empresa_identidad_unica')],
            },
        ),
    ]
