// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMw5WREAajcLAbvfHg2nLQr8UG1U-IkIE',
    appId: '1:969753324327:web:19d8dc9ddacd21f9b81702',
    messagingSenderId: '969753324327',
    projectId: 'la-pocha-9d070',
    authDomain: 'la-pocha-9d070.firebaseapp.com',
    storageBucket: 'la-pocha-9d070.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjePWOjztZ8q1RqWck9hRWS23c7xP4s1s',
    appId: '1:969753324327:android:14be895d0f45b9acb81702',
    messagingSenderId: '969753324327',
    projectId: 'la-pocha-9d070',
    storageBucket: 'la-pocha-9d070.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFjNAgarG1M51wXTTZ_QGS5Gd2UUWTXtI',
    appId: '1:969753324327:ios:9ee7dd14d3434802b81702',
    messagingSenderId: '969753324327',
    projectId: 'la-pocha-9d070',
    storageBucket: 'la-pocha-9d070.firebasestorage.app',
    iosBundleId: 'com.degreeapps.laPocha',
  );
}
