import { PrismaClient, Category } from '@prisma/client';

const prisma = new PrismaClient();

const products = [
  {
    id: 'prod-001',
    name: 'Nike Air Zoom Pegasus 41',
    brand: 'Nike',
    price: '129.99',
    image: 'products/nike-pegasus-41.jpg',
    category: Category.shoes,
    subcategory: 'road running',
    description:
      'Zapatilla versátil para corredores de todos los niveles. Amortiguación React con Zoom Air para mayor respuesta.',
    features: [
      'Amortiguación React',
      'Zoom Air en el antepié',
      'Upper de malla transpirable',
      'Suela de goma duradera',
    ],
    distance: ['5K', '10K', 'half-marathon'],
    surface: ['road'],
    level: ['beginner', 'intermediate'],
    objective: ['daily', 'training'],
    sizes: ['38', '39', '40', '41', '42', '43', '44', '45'],
    colors: ['black', 'white', 'blue'],
    stock: 45,
  },
  {
    id: 'prod-002',
    name: 'Adidas Ultraboost 24',
    brand: 'Adidas',
    price: '189.99',
    image: 'products/adidas-ultraboost-24.jpg',
    category: Category.shoes,
    subcategory: 'road running',
    description:
      'La zapatilla de running premium de Adidas con tecnología Boost para máxima amortiguación y retorno de energía.',
    features: [
      'Tecnología Boost',
      'Upper Primeknit+',
      'Marco de talón en TPU',
      'Suela Continental',
    ],
    distance: ['10K', 'half-marathon', 'marathon'],
    surface: ['road'],
    level: ['intermediate', 'advanced'],
    objective: ['training', 'competition'],
    sizes: ['38', '39', '40', '41', '42', '43', '44', '45', '46'],
    colors: ['black', 'white', 'grey'],
    stock: 32,
  },
  {
    id: 'prod-003',
    name: 'Salomon Speedcross 6',
    brand: 'Salomon',
    price: '139.99',
    image: 'products/salomon-speedcross-6.jpg',
    category: Category.shoes,
    subcategory: 'trail running',
    description:
      'La referencia en trail running agresivo. Suela Contagrip con tacos profundos para máximo agarre en terreno blando.',
    features: [
      'Suela Contagrip MA',
      'Sistema de cordones Quicklace',
      'Protección OrthoLite',
      'Refuerzo lateral',
    ],
    distance: ['10K', 'half-marathon', 'marathon', 'ultra'],
    surface: ['trail'],
    level: ['intermediate', 'advanced'],
    objective: ['competition', 'training'],
    sizes: ['38', '39', '40', '41', '42', '43', '44', '45'],
    colors: ['black', 'red', 'green'],
    stock: 28,
  },
  {
    id: 'prod-004',
    name: 'HOKA Clifton 9',
    brand: 'HOKA',
    price: '144.99',
    image: 'products/hoka-clifton-9.jpg',
    category: Category.shoes,
    subcategory: 'road running',
    description:
      'Máxima amortiguación con peso ultraligero. Ideal para corredores que buscan protección en rodajes largos.',
    features: [
      'Amortiguación máxima',
      'Geometría Meta-Rocker',
      'Upper de malla ligera',
      'Perfil bajo de tacón',
    ],
    distance: ['half-marathon', 'marathon', 'ultra'],
    surface: ['road'],
    level: ['beginner', 'intermediate', 'advanced'],
    objective: ['daily', 'recovery'],
    sizes: ['38', '39', '40', '41', '42', '43', '44', '45', '46'],
    colors: ['white', 'blue', 'grey'],
    stock: 38,
  },
  {
    id: 'prod-005',
    name: 'Brooks Ghost 16',
    brand: 'Brooks',
    price: '134.99',
    image: 'products/brooks-ghost-16.jpg',
    category: Category.shoes,
    subcategory: 'road running',
    description:
      'La zapatilla neutra más vendida de Brooks. Amortiguación DNA LOFT v2 suave y consistente para cada pisada.',
    features: [
      'Amortiguación DNA LOFT v2',
      'Upper 3D Fit Print',
      'Transición segmentada',
      'Suela de goma',
    ],
    distance: ['5K', '10K', 'half-marathon', 'marathon'],
    surface: ['road', 'mixed'],
    level: ['beginner', 'intermediate'],
    objective: ['daily', 'training'],
    sizes: ['37', '38', '39', '40', '41', '42', '43', '44'],
    colors: ['black', 'white', 'pink'],
    stock: 52,
  },
  {
    id: 'prod-006',
    name: 'Nike Dri-FIT Run Division Miler',
    brand: 'Nike',
    price: '54.99',
    image: 'products/nike-dri-fit-miler.jpg',
    category: Category.clothing,
    subcategory: 'camisetas',
    description:
      'Camiseta de running técnica con tecnología Dri-FIT para gestión de la humedad. Diseño reflectante para visibilidad.',
    features: [
      'Tecnología Dri-FIT',
      'Tejido ligero',
      'Diseño reflectante',
      'Corte atlético',
    ],
    distance: ['5K', '10K', 'half-marathon'],
    surface: ['road', 'track'],
    level: ['beginner', 'intermediate', 'advanced'],
    objective: ['training', 'competition', 'daily'],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['black', 'white', 'blue', 'red'],
    stock: 75,
  },
  {
    id: 'prod-007',
    name: 'Adidas Own The Run Shorts',
    brand: 'Adidas',
    price: '34.99',
    image: 'products/adidas-own-the-run-shorts.jpg',
    category: Category.clothing,
    subcategory: 'pantalones cortos',
    description:
      'Shorts de running ligeros con tecnología AEROREADY. Malla interior y bolsillo trasero con cremallera.',
    features: [
      'Tecnología AEROREADY',
      'Malla interior integrada',
      'Bolsillo trasero con cremallera',
      'Cintura elástica',
    ],
    distance: ['5K', '10K', 'half-marathon'],
    surface: ['road', 'track'],
    level: ['beginner', 'intermediate', 'advanced'],
    objective: ['training', 'competition', 'daily'],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['black', 'navy', 'grey'],
    stock: 60,
  },
  {
    id: 'prod-008',
    name: 'Salomon Active Skin 8',
    brand: 'Salomon',
    price: '109.99',
    image: 'products/salomon-active-skin-8.jpg',
    category: Category.accessories,
    subcategory: 'mochilas de hidratación',
    description:
      'Mochila de hidratación trail de 8L con dos flasks Soft Flask de 500ml. Diseño de chaqueta ajustado al cuerpo.',
    features: [
      'Capacidad 8L',
      'Dos Soft Flasks 500ml incluidos',
      'Diseño chaqueta',
      'Bolsillos frontales accesibles',
    ],
    distance: ['marathon', 'ultra'],
    surface: ['trail'],
    level: ['intermediate', 'advanced'],
    objective: ['competition', 'training'],
    sizes: ['S/M', 'M/L'],
    colors: ['black', 'blue'],
    stock: 18,
  },
  {
    id: 'prod-009',
    name: 'Garmin Forerunner 265',
    brand: 'Garmin',
    price: '349.99',
    image: 'products/garmin-forerunner-265.jpg',
    category: Category.accessories,
    subcategory: 'relojes GPS',
    description:
      'Reloj GPS de running con pantalla AMOLED, planes de entrenamiento adaptativos y métricas avanzadas de rendimiento.',
    features: [
      'Pantalla AMOLED 1.3"',
      'GPS multibanda',
      'Planes de entrenamiento adaptativos',
      'Autonomía 15 días',
    ],
    distance: ['5K', '10K', 'half-marathon', 'marathon', 'ultra'],
    surface: ['road', 'trail', 'track', 'mixed'],
    level: ['intermediate', 'advanced'],
    objective: ['training', 'competition'],
    sizes: ['one-size'],
    colors: ['black', 'white', 'blue'],
    stock: 15,
  },
  {
    id: 'prod-010',
    name: 'Compressport Pro Racing Socks v4.0',
    brand: 'Compressport',
    price: '19.99',
    image: 'products/compressport-pro-racing-socks.jpg',
    category: Category.accessories,
    subcategory: 'calcetines',
    description:
      'Calcetines de compresión de carrera para máximo rendimiento. Tecnología R2V2 para soporte del arco y tobillo.',
    features: [
      'Tecnología R2V2',
      'Compresión graduada',
      'Sin costuras',
      'Tejido ultra-ligero',
    ],
    distance: ['5K', '10K', 'half-marathon', 'marathon'],
    surface: ['road', 'track'],
    level: ['beginner', 'intermediate', 'advanced'],
    objective: ['training', 'competition', 'recovery'],
    sizes: ['T1', 'T2', 'T3', 'T4'],
    colors: ['black', 'white', 'red'],
    stock: 120,
  },
  {
    id: 'prod-011',
    name: 'The North Face Movmynt Jacket',
    brand: 'The North Face',
    price: '149.99',
    image: 'products/tnf-movmynt-jacket.jpg',
    category: Category.clothing,
    subcategory: 'chaquetas',
    description:
      'Chaqueta de trail running impermeable y transpirable. Construcción 2.5L con DryVent para condiciones adversas.',
    features: [
      'Membrana DryVent 2.5L',
      'Costuras selladas',
      'Capucha integrada ajustable',
      'Bolsillos con cremallera estanca',
    ],
    distance: ['marathon', 'ultra'],
    surface: ['trail', 'mixed'],
    level: ['intermediate', 'advanced'],
    objective: ['training', 'competition'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['black', 'green', 'orange'],
    stock: 22,
  },
  {
    id: 'prod-012',
    name: 'On Running Cloudmonster 2',
    brand: 'On Running',
    price: '169.99',
    image: 'products/on-cloudmonster-2.jpg',
    category: Category.shoes,
    subcategory: 'road running',
    description:
      'La máxima amortiguación de On con tecnología CloudTec Phase. Ideal para rodajes largos y recuperación activa.',
    features: [
      'CloudTec Phase',
      'Espuma Helion HF',
      'Upper de malla ligera',
      'Suela Missiongrip',
    ],
    distance: ['half-marathon', 'marathon'],
    surface: ['road'],
    level: ['intermediate', 'advanced'],
    objective: ['daily', 'recovery', 'training'],
    sizes: ['38', '39', '40', '41', '42', '43', '44', '45'],
    colors: ['black', 'white', 'glacier'],
    stock: 30,
  },
];

async function main(): Promise<void> {
  for (const product of products) {
    await prisma.product.upsert({
      where: { id: product.id },
      update: product,
      create: product,
    });
  }
  console.log(`Seed completed: ${products.length} products upserted`);
}

main()
  .catch((err: unknown) => {
    console.error('Seed failed:', err);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
