SET search_path TO catalog;

-- Origen del esquema: el esquema "catalog" se crea en infra/compose/init/postgres (Compose).
-- Esta migración define el modelo relacional mínimo del catalog-service (readme §3.2, TASK-HU-005-01):
-- usuario_app, maestros taxonómicos, provincia, arbol, auditoria_catalogo (R3).
-- PK numéricas: ADR-0002 / R9. Coordenadas del ejemplar como NUMERIC (sin geometría PostGIS en este corte).

-- Usuario de aplicación (Keycloak / OIDC).
CREATE TABLE usuario_app (
    usuario_app_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_oidc VARCHAR(255) NOT NULL,
    email VARCHAR(320),
    rol VARCHAR(64),
    creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    modificado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_usuario_app_subject_oidc UNIQUE (subject_oidc)
);

COMMENT ON TABLE usuario_app IS 'Usuario de aplicación vinculado al subject OIDC (Keycloak sub).';

-- Maestros taxonómicos (gestión solo administrador; R8). creado_por / modificado_por → usuario_app.
CREATE TABLE familia (
    familia_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_cientifico VARCHAR(255) NOT NULL,
    nombre_comun VARCHAR(255),
    creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    creado_por BIGINT REFERENCES usuario_app (usuario_app_id),
    modificado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    modificado_por BIGINT REFERENCES usuario_app (usuario_app_id)
);

CREATE TABLE genero (
    genero_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    familia_id BIGINT NOT NULL REFERENCES familia (familia_id),
    nombre_cientifico VARCHAR(255) NOT NULL,
    nombre_comun VARCHAR(255),
    creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    creado_por BIGINT REFERENCES usuario_app (usuario_app_id),
    modificado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    modificado_por BIGINT REFERENCES usuario_app (usuario_app_id)
);

CREATE INDEX idx_genero_familia_id ON genero (familia_id);

CREATE TABLE especie (
    especie_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genero_id BIGINT NOT NULL REFERENCES genero (genero_id),
    nombre_cientifico VARCHAR(255) NOT NULL,
    nombre_comun VARCHAR(255),
    creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    creado_por BIGINT REFERENCES usuario_app (usuario_app_id),
    modificado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    modificado_por BIGINT REFERENCES usuario_app (usuario_app_id)
);

CREATE INDEX idx_especie_genero_id ON especie (genero_id);

CREATE TABLE provincia (
    provincia_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(2) NOT NULL,
    nombre VARCHAR(255) NOT NULL,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    creado_por BIGINT REFERENCES usuario_app (usuario_app_id),
    modificado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    modificado_por BIGINT REFERENCES usuario_app (usuario_app_id)
);

-- Ficha operativa: R1 (especie), R2 (coordenadas). usuario_app_id = colaborador creador.
CREATE TABLE arbol (
    arbol_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    especie_id BIGINT NOT NULL REFERENCES especie (especie_id),
    provincia_id BIGINT NOT NULL REFERENCES provincia (provincia_id),
    usuario_app_id BIGINT NOT NULL REFERENCES usuario_app (usuario_app_id),
    municipio VARCHAR(255),
    descripcion TEXT,
    visibilidad_mapa_publico VARCHAR(64),
    latitud NUMERIC(10, 7) NOT NULL,
    longitud NUMERIC(10, 7) NOT NULL,
    altitud INTEGER,
    estado_publicacion VARCHAR(64),
    creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    creado_por BIGINT REFERENCES usuario_app (usuario_app_id),
    modificado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    modificado_por BIGINT REFERENCES usuario_app (usuario_app_id)
);

CREATE INDEX idx_arbol_especie_id ON arbol (especie_id);
CREATE INDEX idx_arbol_provincia_id ON arbol (provincia_id);
CREATE INDEX idx_arbol_usuario_app_id ON arbol (usuario_app_id);

-- R3 — auditoría de operaciones relevantes en catálogo (detalle en TASK-HU-005-07).
CREATE TABLE auditoria_catalogo (
    auditoria_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_usuario_app_id BIGINT NOT NULL REFERENCES usuario_app (usuario_app_id),
    operacion VARCHAR(128) NOT NULL,
    ocurrido_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    datos_previos_resumen TEXT,
    datos_nuevos_resumen TEXT
);

CREATE INDEX idx_auditoria_actor ON auditoria_catalogo (actor_usuario_app_id);
CREATE INDEX idx_auditoria_ocurrido ON auditoria_catalogo (ocurrido_en);
