-- =============================================================================
-- catalog-service — esquema relacional (DDL único, MVP)
-- =============================================================================
-- Origen: readme §3.2, data-model R1–R3/R8/R9, ADR-0002, ADR-0004.
-- El esquema "catalog" lo crea Flyway (create-schemas=true) o init Compose.
-- Semillas de maestros: V2__seed_maestros_inicial.sql (datos, no DDL).
-- =============================================================================

-- Búsquedas insensibles a acentos en maestros y listados (idempotente).
-- El init de Compose también instala unaccent en public.
CREATE EXTENSION IF NOT EXISTS unaccent;

SET search_path TO catalog;

-- Usuario de aplicación (Keycloak / OIDC). Roles solo en JWT (ADR-0004).
CREATE TABLE usuario_app (
    usuario_app_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_oidc VARCHAR(255) NOT NULL,
    email VARCHAR(320),
    nombre VARCHAR(255),
    creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    modificado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_usuario_app_subject_oidc UNIQUE (subject_oidc)
);

COMMENT ON TABLE usuario_app IS 'Usuario de aplicación vinculado al subject OIDC (Keycloak sub).';
COMMENT ON COLUMN usuario_app.nombre IS 'Nombre para mostrar derivado del token (name o given_name+family_name); nullable.';

-- Maestros taxonómicos (gestión solo administrador; R8). creado_por / modificado_por → usuario_app.
CREATE TABLE familia (
    familia_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_cientifico VARCHAR(255) NOT NULL,
    nombre_comun VARCHAR(255),
    creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    creado_por BIGINT REFERENCES usuario_app (usuario_app_id),
    modificado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    modificado_por BIGINT REFERENCES usuario_app (usuario_app_id),
    CONSTRAINT uq_familia_nombre_cientifico UNIQUE (nombre_cientifico)
);

CREATE TABLE genero (
    genero_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    familia_id BIGINT NOT NULL REFERENCES familia (familia_id),
    nombre_cientifico VARCHAR(255) NOT NULL,
    nombre_comun VARCHAR(255),
    creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    creado_por BIGINT REFERENCES usuario_app (usuario_app_id),
    modificado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    modificado_por BIGINT REFERENCES usuario_app (usuario_app_id),
    CONSTRAINT uq_genero_familia_nombre_cientifico UNIQUE (familia_id, nombre_cientifico)
);

CREATE INDEX idx_genero_familia_id ON genero (familia_id);

CREATE TABLE especie (
    especie_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genero_id BIGINT NOT NULL REFERENCES genero (genero_id),
    nombre_cientifico VARCHAR(255) NOT NULL,
    nombre_comun VARCHAR(255),
    creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    creado_por BIGINT REFERENCES usuario_app (usuario_app_id),
    modificado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    modificado_por BIGINT REFERENCES usuario_app (usuario_app_id),
    CONSTRAINT uq_especie_genero_nombre_cientifico UNIQUE (genero_id, nombre_cientifico)
);

CREATE INDEX idx_especie_genero_id ON especie (genero_id);

CREATE TABLE provincia (
    provincia_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(2) NOT NULL,
    nombre VARCHAR(255) NOT NULL,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    creado_por BIGINT REFERENCES usuario_app (usuario_app_id),
    modificado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    modificado_por BIGINT REFERENCES usuario_app (usuario_app_id),
    CONSTRAINT uq_provincia_codigo UNIQUE (codigo)
);

-- Ficha operativa: R1 (especie), R2 (coordenadas). usuario_app_id = colaborador creador.
CREATE TABLE ejemplar (
    ejemplar_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    especie_id BIGINT NOT NULL REFERENCES especie (especie_id),
    provincia_id BIGINT NOT NULL REFERENCES provincia (provincia_id),
    usuario_app_id BIGINT NOT NULL REFERENCES usuario_app (usuario_app_id),
    municipio VARCHAR(255),
    descripcion TEXT,
    visibilidad_mapa_publico VARCHAR(64),
    latitud NUMERIC(10, 7) NOT NULL,
    longitud NUMERIC(10, 7) NOT NULL,
    altitud INTEGER,
    estado_publicacion VARCHAR(64),
    creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    creado_por BIGINT REFERENCES usuario_app (usuario_app_id),
    modificado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    modificado_por BIGINT REFERENCES usuario_app (usuario_app_id),
    CONSTRAINT ck_ejemplar_estado_publicacion
        CHECK (estado_publicacion IS NULL OR estado_publicacion IN ('BORRADOR', 'PUBLICADO')),
    CONSTRAINT ck_ejemplar_visibilidad_mapa
        CHECK (visibilidad_mapa_publico IS NULL OR visibilidad_mapa_publico IN ('PRIVADO', 'PUBLICO'))
);

CREATE INDEX idx_ejemplar_especie_id ON ejemplar (especie_id);
CREATE INDEX idx_ejemplar_provincia_id ON ejemplar (provincia_id);
CREATE INDEX idx_ejemplar_usuario_app_id ON ejemplar (usuario_app_id);

-- Listados públicos: PublicEjemplarReadRepository filtra PUBLICADO + PUBLICO.
CREATE INDEX idx_ejemplar_publicado_publico
    ON ejemplar (especie_id, provincia_id)
    WHERE estado_publicacion = 'PUBLICADO'
      AND visibilidad_mapa_publico = 'PUBLICO';

-- R3 — auditoría de operaciones relevantes en catálogo.
CREATE TABLE auditoria_catalogo (
    auditoria_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_usuario_app_id BIGINT NOT NULL REFERENCES usuario_app (usuario_app_id),
    operacion VARCHAR(128) NOT NULL,
    ocurrido_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    datos_previos_resumen TEXT,
    datos_nuevos_resumen TEXT
);

CREATE INDEX idx_auditoria_actor ON auditoria_catalogo (actor_usuario_app_id);
CREATE INDEX idx_auditoria_ocurrido ON auditoria_catalogo (ocurrido_en);

-- Identificador único de mensaje Kafka (EJEMPLAR_CREADO); sin tabla EVENTO_CATALOGO en catálogo.
CREATE SEQUENCE seq_ejemplar_evento_id
    INCREMENT BY 1
    MINVALUE 1
    NO MAXVALUE
    START WITH 1
    CACHE 1;
