apiVersion: apps/v1
kind: Deployment
metadata:
  name: aura-api
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aura-frontend
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aura-worker-email
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aura-worker-whatsapp
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aura-worker-ssg
spec:
  replicas: 1
