/** All user-facing copy in one place. Failure copy is the portal's own calm wording
 *  keyed by outcome — the streamer error body is treated as opaque (design D-P3). */
export const COPY = {
  homeHeading: "Live streams",
  startAction: "Start streaming",
  loading: "Loading streams…",
  emptyState: "No one is streaming right now.",
  loadError: "Couldn't load streams right now. Refresh to try again.",

  startConfirmHeading: "Are you sure to start stream?",
  titleLabel: "Title",
  descriptionLabel: "Description (optional)",
  startConfirm: "Start",
  cancel: "Cancel",
  titleRequired: "A title is required.",
  descriptionTooLong: "Description must be 100 characters or fewer.",
  startFailed: "Couldn't start the stream. Check your input and try again.",
  alreadyStreaming: "You already have an active stream.",

  // Auth
  signInAction: "Sign in",
  signOutAction: "Sign out",
  signInHeading: "Sign in to QuickChat",
  emailLabel: "Email",
  emailPlaceholder: "you@example.com",
  emailInvalid: "Enter a valid email address.",
  sendMagicLink: "Send magic link",
  inboxHeading: "Check your inbox",
  inboxBody: "We sent a sign-in link to your email. Open it to continue.",
  signInToStart: "Sign in to start streaming.",
  signInToChat: "Sign in to chat",
  signInToContinue: "Sign in to continue.",
  verifying: "Signing you in…",
  linkFailed: "That sign-in link didn't work. Please try signing in again.",
  signOutWarnPublishing: "Signing out will end your live stream. Continue?",
  signOutConfirm: "Sign out and end stream",
  keepStreaming: "Keep streaming",

  endAction: "End stream",
  endFailed: "Couldn't end the stream right now. Try again.",
  endNotAllowed: "You can't end this stream.",
  streamEnded: "This stream has ended.",
  redirecting: "Taking you home…",

  // Room + chat
  cameraPlaceholder: "Camera preview will appear here.",
  chatHeading: "Chat",
  hideChat: "Hide chat",
  showChat: "Show chat",
  chatConnecting: "Connecting…",
  chatReconnecting: "Reconnecting…",
  chatEnded: "This room has ended.",
  chatLoadOlder: "Loading earlier messages…",
  streamerLabel: "STREAMER",
  composerPlaceholder: "Say something…",
  sendAction: "Send",
  messageRequired: "Type a message first.",
  messageTooLong: "Message must be 500 characters or fewer.",
  messageRejected: "That message couldn't be sent.",

  // Media
  mediaLoading: "Connecting media…",
  mediaError: "Media is unavailable right now.",
  mediaOffline: "No one is on air right now.",
  mediaReconnecting: "Reconnecting media…",
  mediaPrejoin: "Set up your camera and microphone, then go live.",
  goLiveAction: "Go live",
  muteMicAction: "Mute mic",
  unmuteMicAction: "Unmute mic",
  cameraOffAction: "Camera off",
  cameraOnAction: "Camera on",
  tapToUnmute: "Tap to unmute",

  notFound: "Page not found.",
  backHome: "Back to home",
} as const;
