// Mocks generated by Mockito 5.4.6 from annotations
// in la_pocha/test/features/game_setup/presentation/bloc/add_players_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:la_pocha/features/game_setup/domain/entities/game.dart' as _i2;
import 'package:la_pocha/features/game_setup/domain/usecases/add_player_from_favorite_usecase.dart'
    as _i6;
import 'package:la_pocha/features/game_setup/domain/usecases/add_player_usecase.dart'
    as _i5;
import 'package:la_pocha/features/game_setup/domain/usecases/get_game_by_id_usecase.dart'
    as _i3;
import 'package:la_pocha/features/game_setup/domain/usecases/remove_player_usecase.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGame_0 extends _i1.SmartFake implements _i2.Game {
  _FakeGame_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetGameByIdUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetGameByIdUseCase extends _i1.Mock
    implements _i3.GetGameByIdUseCase {
  @override
  _i4.Future<_i2.Game?> call(String? gameId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [gameId]),
            returnValue: _i4.Future<_i2.Game?>.value(),
            returnValueForMissingStub: _i4.Future<_i2.Game?>.value(),
          )
          as _i4.Future<_i2.Game?>);
}

/// A class which mocks [AddPlayerUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddPlayerUseCase extends _i1.Mock implements _i5.AddPlayerUseCase {
  @override
  _i4.Future<_i2.Game> call({required String? gameId, required String? name}) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#gameId: gameId, #name: name}),
            returnValue: _i4.Future<_i2.Game>.value(
              _FakeGame_0(
                this,
                Invocation.method(#call, [], {#gameId: gameId, #name: name}),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.Game>.value(
              _FakeGame_0(
                this,
                Invocation.method(#call, [], {#gameId: gameId, #name: name}),
              ),
            ),
          )
          as _i4.Future<_i2.Game>);
}

/// A class which mocks [AddPlayerFromFavoriteUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddPlayerFromFavoriteUseCase extends _i1.Mock
    implements _i6.AddPlayerFromFavoriteUseCase {
  @override
  _i4.Future<_i2.Game> call({
    required String? gameId,
    required String? favoriteId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #gameId: gameId,
              #favoriteId: favoriteId,
            }),
            returnValue: _i4.Future<_i2.Game>.value(
              _FakeGame_0(
                this,
                Invocation.method(#call, [], {
                  #gameId: gameId,
                  #favoriteId: favoriteId,
                }),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.Game>.value(
              _FakeGame_0(
                this,
                Invocation.method(#call, [], {
                  #gameId: gameId,
                  #favoriteId: favoriteId,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Game>);
}

/// A class which mocks [RemovePlayerUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemovePlayerUseCase extends _i1.Mock
    implements _i7.RemovePlayerUseCase {
  @override
  _i4.Future<_i2.Game?> call({
    required String? gameId,
    required String? playerId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #gameId: gameId,
              #playerId: playerId,
            }),
            returnValue: _i4.Future<_i2.Game?>.value(),
            returnValueForMissingStub: _i4.Future<_i2.Game?>.value(),
          )
          as _i4.Future<_i2.Game?>);
}
