// <auto-generated />
using System;
using InkLink.Api.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InkLink.Api.Migrations
{
    [DbContext(typeof(InkLinkDbContext))]
    [Migration("20260714215718_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InkLink.Api.Domain.Entities.ArtistProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("address");

                    b.Property<string>("ArtistType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("artist_type");

                    b.Property<string>("Bio")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("bio");

                    b.Property<string>("CancellationPolicy")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("cancellation_policy");

                    b.Property<string>("Commune")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("commune");

                    b.Property<int>("DepositPercentage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(30)
                        .HasColumnName("deposit_percentage");

                    b.Property<int>("HourlyRate")
                        .HasColumnType("integer")
                        .HasColumnName("hourly_rate");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(10, 8)
                        .HasColumnType("numeric(10,8)")
                        .HasColumnName("latitude");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(11, 8)
                        .HasColumnType("numeric(11,8)")
                        .HasColumnName("longitude");

                    b.Property<int>("MinSessionPrice")
                        .HasColumnType("integer")
                        .HasColumnName("min_session_price");

                    b.Property<decimal>("RatingAvg")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("rating_avg");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<int>("TotalReviews")
                        .HasColumnType("integer")
                        .HasColumnName("total_reviews");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("YearsExperience")
                        .HasColumnType("integer")
                        .HasColumnName("years_experience");

                    b.HasKey("Id")
                        .HasName("pk_artist_profiles");

                    b.HasIndex("Commune")
                        .HasDatabaseName("ix_artist_profiles_commune");

                    b.HasIndex("IsPublished")
                        .HasDatabaseName("ix_artist_profiles_is_published");

                    b.HasIndex("RatingAvg")
                        .HasDatabaseName("ix_artist_profiles_rating_avg");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_artist_profiles_slug");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_artist_profiles_user_id");

                    b.ToTable("artist_profiles", (string)null);
                });

            modelBuilder.Entity("InkLink.Api.Domain.Entities.ArtistStyle", b =>
                {
                    b.Property<Guid>("ArtistProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("artist_profile_id");

                    b.Property<Guid>("StyleId")
                        .HasColumnType("uuid")
                        .HasColumnName("style_id");

                    b.HasKey("ArtistProfileId", "StyleId")
                        .HasName("pk_artist_styles");

                    b.HasIndex("StyleId")
                        .HasDatabaseName("ix_artist_styles_style_id");

                    b.ToTable("artist_styles", (string)null);
                });

            modelBuilder.Entity("InkLink.Api.Domain.Entities.Availability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ArtistProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("artist_profile_id");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_week");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("end_time");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("SlotDurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("slot_duration_minutes");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time");

                    b.HasKey("Id")
                        .HasName("pk_availabilities");

                    b.HasIndex("ArtistProfileId")
                        .HasDatabaseName("ix_availabilities_artist_profile_id");

                    b.ToTable("availabilities", (string)null);
                });

            modelBuilder.Entity("InkLink.Api.Domain.Entities.Award", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ArtistProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("artist_profile_id");

                    b.Property<string>("BadgeIconUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("badge_icon_url");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_name");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_awards");

                    b.HasIndex("ArtistProfileId")
                        .HasDatabaseName("ix_awards_artist_profile_id");

                    b.ToTable("awards", (string)null);
                });

            modelBuilder.Entity("InkLink.Api.Domain.Entities.BlockedDate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ArtistProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("artist_profile_id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("Reason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reason");

                    b.HasKey("Id")
                        .HasName("pk_blocked_dates");

                    b.HasIndex("ArtistProfileId", "Date")
                        .IsUnique()
                        .HasDatabaseName("ix_blocked_dates_artist_profile_id_date");

                    b.ToTable("blocked_dates", (string)null);
                });

            modelBuilder.Entity("InkLink.Api.Domain.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ArtistProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("artist_profile_id");

                    b.Property<string>("BodyZone")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("body_zone");

                    b.Property<DateOnly>("BookingDate")
                        .HasColumnType("date")
                        .HasColumnName("booking_date");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DepositAmount")
                        .HasColumnType("integer")
                        .HasColumnName("deposit_amount");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("end_time");

                    b.Property<int>("EstimatedPriceMax")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_price_max");

                    b.Property<int>("EstimatedPriceMin")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_price_min");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsColor")
                        .HasColumnType("boolean")
                        .HasColumnName("is_color");

                    b.Property<bool>("IsCoverup")
                        .HasColumnType("boolean")
                        .HasColumnName("is_coverup");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.PrimitiveCollection<string>("ReferenceImages")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("reference_images");

                    b.Property<string>("SizeReference")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("size_reference");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid?>("StyleId")
                        .HasColumnType("uuid")
                        .HasColumnName("style_id");

                    b.HasKey("Id")
                        .HasName("pk_bookings");

                    b.HasIndex("ArtistProfileId")
                        .HasDatabaseName("ix_bookings_artist_profile_id");

                    b.HasIndex("BookingDate")
                        .HasDatabaseName("ix_bookings_booking_date");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_bookings_client_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_bookings_status");

                    b.HasIndex("StyleId")
                        .HasDatabaseName("ix_bookings_style_id");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("InkLink.Api.Domain.Entities.Certification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ArtistProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("artist_profile_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("issuer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.Property<DateOnly>("ValidUntil")
                        .HasColumnType("date")
                        .HasColumnName("valid_until");

                    b.HasKey("Id")
                        .HasName("pk_certifications");

                    b.HasIndex("ArtistProfileId")
                        .HasDatabaseName("ix_certifications_artist_profile_id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_certifications_is_active");

                    b.ToTable("certifications", (string)null);
                });

            modelBuilder.Entity("InkLink.Api.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Amount")
                        .HasColumnType("integer")
                        .HasColumnName("amount");

                    b.Property<int>("ArtistAmount")
                        .HasColumnType("integer")
                        .HasColumnName("artist_amount");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<string>("FlowTransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("flow_transaction_id");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<int>("PlatformFee")
                        .HasColumnType("integer")
                        .HasColumnName("platform_fee");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_payments");

                    b.HasIndex("BookingId")
                        .IsUnique()
                        .HasDatabaseName("ix_payments_booking_id");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("InkLink.Api.Domain.Entities.PortfolioItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ArtistProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("artist_profile_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean")
                        .HasColumnName("is_featured");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<Guid>("StyleId")
                        .HasColumnType("uuid")
                        .HasColumnName("style_id");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("thumbnail_url");

                    b.HasKey("Id")
                        .HasName("pk_portfolio_items");

                    b.HasIndex("ArtistProfileId")
                        .HasDatabaseName("ix_portfolio_items_artist_profile_id");

                    b.HasIndex("StyleId")
                        .HasDatabaseName("ix_portfolio_items_style_id");

                    b.ToTable("portfolio_items", (string)null);
                });

            modelBuilder.Entity("InkLink.Api.Domain.Entities.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ArtistProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("artist_profile_id");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("RatingCustomerService")
                        .HasColumnType("integer")
                        .HasColumnName("rating_customer_service");

                    b.Property<int>("RatingHygiene")
                        .HasColumnType("integer")
                        .HasColumnName("rating_hygiene");

                    b.Property<int>("RatingPainManagement")
                        .HasColumnType("integer")
                        .HasColumnName("rating_pain_management");

                    b.Property<int>("RatingResult")
                        .HasColumnType("integer")
                        .HasColumnName("rating_result");

                    b.Property<string>("TattooPhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("tattoo_photo_url");

                    b.HasKey("Id")
                        .HasName("pk_reviews");

                    b.HasIndex("ArtistProfileId")
                        .HasDatabaseName("ix_reviews_artist_profile_id");

                    b.HasIndex("BookingId")
                        .IsUnique()
                        .HasDatabaseName("ix_reviews_booking_id");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_reviews_client_id");

                    b.ToTable("reviews", (string)null);
                });

            modelBuilder.Entity("InkLink.Api.Domain.Entities.Sponsorship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ArtistProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("artist_profile_id");

                    b.Property<string>("BrandLogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("brand_logo_url");

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("brand_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("RelationshipType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("relationship_type");

                    b.HasKey("Id")
                        .HasName("pk_sponsorships");

                    b.HasIndex("ArtistProfileId")
                        .HasDatabaseName("ix_sponsorships_artist_profile_id");

                    b.ToTable("sponsorships", (string)null);
                });

            modelBuilder.Entity("InkLink.Api.Domain.Entities.TattooStyle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("icon_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_tattoo_styles");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_tattoo_styles_name");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_tattoo_styles_slug");

                    b.ToTable("tattoo_styles", (string)null);
                });

            modelBuilder.Entity("InkLink.Api.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verified");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("InkLink.Api.Domain.Entities.ArtistProfile", b =>
                {
                    b.HasOne("InkLink.Api.Domain.Entities.User", "User")
                        .WithOne("ArtistProfile")
                        .HasForeignKey("InkLink.Api.Domain.Entities.ArtistProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_artist_profiles_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InkLink.Api.Domain.Entities.ArtistStyle", b =>
                {
                    b.HasOne("InkLink.Api.Domain.Entities.ArtistProfile", "ArtistProfile")
                        .WithMany("ArtistStyles")
                        .HasForeignKey("ArtistProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_artist_styles_artist_profiles_artist_profile_id");

                    b.HasOne("InkLink.Api.Domain.Entities.TattooStyle", "Style")
                        .WithMany("ArtistStyles")
                        .HasForeignKey("StyleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_artist_styles_tattoo_styles_style_id");

                    b.Navigation("ArtistProfile");

                    b.Navigation("Style");
                });

            modelBuilder.Entity("InkLink.Api.Domain.Entities.Availability", b =>
                {
                    b.HasOne("InkLink.Api.Domain.Entities.ArtistProfile", "ArtistProfile")
                        .WithMany("Availabilities")
                        .HasForeignKey("ArtistProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_availabilities_artist_profiles_artist_profile_id");

                    b.Navigation("ArtistProfile");
                });

            modelBuilder.Entity("InkLink.Api.Domain.Entities.Award", b =>
                {
                    b.HasOne("InkLink.Api.Domain.Entities.ArtistProfile", "ArtistProfile")
                        .WithMany("Awards")
                        .HasForeignKey("ArtistProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_awards_artist_profiles_artist_profile_id");

                    b.Navigation("ArtistProfile");
                });

            modelBuilder.Entity("InkLink.Api.Domain.Entities.BlockedDate", b =>
                {
                    b.HasOne("InkLink.Api.Domain.Entities.ArtistProfile", "ArtistProfile")
                        .WithMany("BlockedDates")
                        .HasForeignKey("ArtistProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_blocked_dates_artist_profiles_artist_profile_id");

                    b.Navigation("ArtistProfile");
                });

            modelBuilder.Entity("InkLink.Api.Domain.Entities.Booking", b =>
                {
                    b.HasOne("InkLink.Api.Domain.Entities.ArtistProfile", "ArtistProfile")
                        .WithMany("Bookings")
                        .HasForeignKey("ArtistProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_artist_profiles_artist_profile_id");

                    b.HasOne("InkLink.Api.Domain.Entities.User", "Client")
                        .WithMany("Bookings")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_users_client_id");

                    b.HasOne("InkLink.Api.Domain.Entities.TattooStyle", "Style")
                        .WithMany()
                        .HasForeignKey("StyleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_bookings_tattoo_styles_style_id");

                    b.Navigation("ArtistProfile");

                    b.Navigation("Client");

                    b.Navigation("Style");
                });

            modelBuilder.Entity("InkLink.Api.Domain.Entities.Certification", b =>
                {
                    b.HasOne("InkLink.Api.Domain.Entities.ArtistProfile", "ArtistProfile")
                        .WithMany("Certifications")
                        .HasForeignKey("ArtistProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_certifications_artist_profiles_artist_profile_id");

                    b.Navigation("ArtistProfile");
                });

            modelBuilder.Entity("InkLink.Api.Domain.Entities.Payment", b =>
                {
                    b.HasOne("InkLink.Api.Domain.Entities.Booking", "Booking")
                        .WithOne("Payment")
                        .HasForeignKey("InkLink.Api.Domain.Entities.Payment", "BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payments_bookings_booking_id");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("InkLink.Api.Domain.Entities.PortfolioItem", b =>
                {
                    b.HasOne("InkLink.Api.Domain.Entities.ArtistProfile", "ArtistProfile")
                        .WithMany("PortfolioItems")
                        .HasForeignKey("ArtistProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_portfolio_items_artist_profiles_artist_profile_id");

                    b.HasOne("InkLink.Api.Domain.Entities.TattooStyle", "Style")
                        .WithMany("PortfolioItems")
                        .HasForeignKey("StyleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_portfolio_items_tattoo_styles_style_id");

                    b.Navigation("ArtistProfile");

                    b.Navigation("Style");
                });

            modelBuilder.Entity("InkLink.Api.Domain.Entities.Review", b =>
                {
                    b.HasOne("InkLink.Api.Domain.Entities.ArtistProfile", "ArtistProfile")
                        .WithMany()
                        .HasForeignKey("ArtistProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_artist_profiles_artist_profile_id");

                    b.HasOne("InkLink.Api.Domain.Entities.Booking", "Booking")
                        .WithOne("Review")
                        .HasForeignKey("InkLink.Api.Domain.Entities.Review", "BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_bookings_booking_id");

                    b.HasOne("InkLink.Api.Domain.Entities.User", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_users_client_id");

                    b.Navigation("ArtistProfile");

                    b.Navigation("Booking");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("InkLink.Api.Domain.Entities.Sponsorship", b =>
                {
                    b.HasOne("InkLink.Api.Domain.Entities.ArtistProfile", "ArtistProfile")
                        .WithMany("Sponsorships")
                        .HasForeignKey("ArtistProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sponsorships_artist_profiles_artist_profile_id");

                    b.Navigation("ArtistProfile");
                });

            modelBuilder.Entity("InkLink.Api.Domain.Entities.ArtistProfile", b =>
                {
                    b.Navigation("ArtistStyles");

                    b.Navigation("Availabilities");

                    b.Navigation("Awards");

                    b.Navigation("BlockedDates");

                    b.Navigation("Bookings");

                    b.Navigation("Certifications");

                    b.Navigation("PortfolioItems");

                    b.Navigation("Sponsorships");
                });

            modelBuilder.Entity("InkLink.Api.Domain.Entities.Booking", b =>
                {
                    b.Navigation("Payment");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("InkLink.Api.Domain.Entities.TattooStyle", b =>
                {
                    b.Navigation("ArtistStyles");

                    b.Navigation("PortfolioItems");
                });

            modelBuilder.Entity("InkLink.Api.Domain.Entities.User", b =>
                {
                    b.Navigation("ArtistProfile");

                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
