// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TejaFlow.Infrastructure.Persistence;

#nullable disable

namespace TejaFlow.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TejaFlowDbContext))]
    [Migration("20260907051824_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TejaFlow.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<string>("DireccionEntrega")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("direccion_entrega");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("razon_social");

                    b.Property<string>("RfcNit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("rfc_nit");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("telefono");

                    b.Property<string>("TipoCliente")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("tipo_cliente");

                    b.HasKey("IdCliente");

                    b.HasIndex("Email");

                    b.HasIndex("RfcNit")
                        .IsUnique();

                    b.ToTable("CLIENTE", (string)null);

                    b.HasData(
                        new
                        {
                            IdCliente = 1,
                            DireccionEntrega = "Av. Tecnologico 1200, Chihuahua",
                            Email = "compras@constructoranorte.test",
                            RazonSocial = "Constructora Norte SA de CV",
                            RfcNit = "CNO260101AB1",
                            Telefono = "6141000001",
                            TipoCliente = "Mayorista"
                        },
                        new
                        {
                            IdCliente = 2,
                            DireccionEntrega = "Carretera Aldama Km 8, Chihuahua",
                            Email = "ventas@techofirme.test",
                            RazonSocial = "Distribuidora Techo Firme",
                            RfcNit = "DTF260101AB2",
                            Telefono = "6141000002",
                            TipoCliente = "Distribuidor"
                        });
                });

            modelBuilder.Entity("TejaFlow.Domain.Entities.DespachoFlete", b =>
                {
                    b.Property<int>("IdDespacho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_despacho");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDespacho"));

                    b.Property<string>("DireccionEntrega")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("direccion_entrega");

                    b.Property<string>("EstadoEntrega")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("estado_entrega");

                    b.Property<DateTime?>("FechaEntregaReal")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_entrega_real");

                    b.Property<DateTime?>("FechaSalida")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_salida");

                    b.Property<int>("IdPedido")
                        .HasColumnType("int")
                        .HasColumnName("id_pedido");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<string>("IndicacionesDescarga")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("indicaciones_descarga");

                    b.Property<decimal>("PesoTotalCargaKg")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("peso_total_carga_kg");

                    b.Property<string>("PlacasVehiculo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("placas_vehiculo");

                    b.Property<string>("TipoCamion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("tipo_camion");

                    b.HasKey("IdDespacho");

                    b.HasIndex("EstadoEntrega");

                    b.HasIndex("IdPedido");

                    b.HasIndex("IdUsuario");

                    b.ToTable("DESPACHO_FLETE", null, t =>
                        {
                            t.HasCheckConstraint("CK_DESPACHO_ESTADO", "estado_entrega IN ('EnRuta', 'Entregado', 'Cancelado')");

                            t.HasCheckConstraint("CK_DESPACHO_PESO", "peso_total_carga_kg > 0");
                        });
                });

            modelBuilder.Entity("TejaFlow.Domain.Entities.DetallePedido", b =>
                {
                    b.Property<int>("IdDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_detalle");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalle"));

                    b.Property<int>("CantidadDespachada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("cantidad_despachada");

                    b.Property<int>("CantidadSolicitada")
                        .HasColumnType("int")
                        .HasColumnName("cantidad_solicitada");

                    b.Property<int>("IdPedido")
                        .HasColumnType("int")
                        .HasColumnName("id_pedido");

                    b.Property<int>("IdTeja")
                        .HasColumnType("int")
                        .HasColumnName("id_teja");

                    b.Property<decimal>("MetrosCuadradosCalculados")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("metros_cuadrados_calculados");

                    b.Property<decimal>("PendienteTechoGrados")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("pendiente_techo_grados");

                    b.Property<decimal>("PrecioUnitarioAplicado")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precio_unitario_aplicado");

                    b.HasKey("IdDetalle");

                    b.HasIndex("IdPedido");

                    b.HasIndex("IdTeja");

                    b.ToTable("DETALLE_PEDIDO", null, t =>
                        {
                            t.HasCheckConstraint("CK_DETALLE_CALCULO_TECHO", "pendiente_techo_grados >= 0 AND pendiente_techo_grados <= 90 AND metros_cuadrados_calculados > 0");

                            t.HasCheckConstraint("CK_DETALLE_CANTIDADES", "cantidad_solicitada > 0 AND cantidad_despachada >= 0 AND cantidad_despachada <= cantidad_solicitada");

                            t.HasCheckConstraint("CK_DETALLE_PRECIO", "precio_unitario_aplicado >= 0");
                        });

                    b.HasData(
                        new
                        {
                            IdDetalle = 1,
                            CantidadDespachada = 0,
                            CantidadSolicitada = 1694,
                            IdPedido = 1,
                            IdTeja = 1,
                            MetrosCuadradosCalculados = 138.56m,
                            PendienteTechoGrados = 30.00m,
                            PrecioUnitarioAplicado = 22.50m
                        });
                });

            modelBuilder.Entity("TejaFlow.Domain.Entities.LoteProduccion", b =>
                {
                    b.Property<int>("IdLote")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_lote");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLote"));

                    b.Property<int>("CantidadActual")
                        .HasColumnType("int")
                        .HasColumnName("cantidad_actual");

                    b.Property<int>("CantidadInicial")
                        .HasColumnType("int")
                        .HasColumnName("cantidad_inicial");

                    b.Property<string>("CodigoLote")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("codigo_lote");

                    b.Property<DateTime>("FechaEntrada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_entrada")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("IdTeja")
                        .HasColumnType("int")
                        .HasColumnName("id_teja");

                    b.HasKey("IdLote");

                    b.HasIndex("CodigoLote")
                        .IsUnique();

                    b.HasIndex("IdTeja", "CantidadActual")
                        .HasDatabaseName("IX_LOTE_TEJA_ACTUAL");

                    b.ToTable("LOTE_PRODUCCION", null, t =>
                        {
                            t.HasCheckConstraint("CK_LOTE_CANTIDAD_ACTUAL", "cantidad_actual >= 0");

                            t.HasCheckConstraint("CK_LOTE_CANTIDAD_INICIAL", "cantidad_inicial > 0");
                        });

                    b.HasData(
                        new
                        {
                            IdLote = 1,
                            CantidadActual = 5000,
                            CantidadInicial = 5000,
                            CodigoLote = "LOT-2026-B01",
                            FechaEntrada = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            IdTeja = 1
                        },
                        new
                        {
                            IdLote = 2,
                            CantidadActual = 3000,
                            CantidadInicial = 3000,
                            CodigoLote = "LOT-2026-B02",
                            FechaEntrada = new DateTime(2026, 1, 20, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            IdTeja = 1
                        },
                        new
                        {
                            IdLote = 3,
                            CantidadActual = 4500,
                            CantidadInicial = 4500,
                            CodigoLote = "LOT-2026-C01",
                            FechaEntrada = new DateTime(2026, 2, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            IdTeja = 2
                        },
                        new
                        {
                            IdLote = 4,
                            CantidadActual = 2200,
                            CantidadInicial = 2200,
                            CodigoLote = "LOT-2026-F01",
                            FechaEntrada = new DateTime(2026, 2, 10, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            IdTeja = 3
                        });
                });

            modelBuilder.Entity("TejaFlow.Domain.Entities.MermaRotura", b =>
                {
                    b.Property<int>("IdMerma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_merma");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMerma"));

                    b.Property<int>("CantidadRotas")
                        .HasColumnType("int")
                        .HasColumnName("cantidad_rotas");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_registro")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("IdLote")
                        .HasColumnType("int")
                        .HasColumnName("id_lote");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("motivo");

                    b.HasKey("IdMerma");

                    b.HasIndex("IdLote");

                    b.HasIndex("IdUsuario");

                    b.ToTable("MERMA_ROTURA", null, t =>
                        {
                            t.HasCheckConstraint("CK_MERMA_CANTIDAD_ROTAS", "cantidad_rotas > 0");
                        });

                    b.HasData(
                        new
                        {
                            IdMerma = 1,
                            CantidadRotas = 25,
                            FechaRegistro = new DateTime(2026, 2, 12, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            IdLote = 1,
                            IdUsuario = 3,
                            Motivo = "Rotura detectada durante acomodo en patio"
                        });
                });

            modelBuilder.Entity("TejaFlow.Domain.Entities.MovimientoInventario", b =>
                {
                    b.Property<int>("IdMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_movimiento");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMovimiento"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("cantidad");

                    b.Property<DateTime>("FechaMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_movimiento")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("IdLote")
                        .HasColumnType("int")
                        .HasColumnName("id_lote");

                    b.Property<int?>("IdMerma")
                        .HasColumnType("int")
                        .HasColumnName("id_merma");

                    b.Property<int?>("IdPedido")
                        .HasColumnType("int")
                        .HasColumnName("id_pedido");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("referencia");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("tipo_movimiento");

                    b.HasKey("IdMovimiento");

                    b.HasIndex("IdMerma");

                    b.HasIndex("IdPedido");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("IdLote", "FechaMovimiento");

                    b.ToTable("MOVIMIENTO_INVENTARIO", null, t =>
                        {
                            t.HasCheckConstraint("CK_MOVIMIENTO_CANTIDAD", "cantidad <> 0");

                            t.HasCheckConstraint("CK_MOVIMIENTO_TIPO", "tipo_movimiento IN ('EntradaLote', 'Venta', 'Merma', 'DespachoParcial', 'AjusteManual')");
                        });

                    b.HasData(
                        new
                        {
                            IdMovimiento = 1,
                            Cantidad = -25,
                            FechaMovimiento = new DateTime(2026, 2, 12, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            IdLote = 1,
                            IdMerma = 1,
                            IdUsuario = 3,
                            Referencia = "MERMA-SEED-0001",
                            TipoMovimiento = "Merma"
                        });
                });

            modelBuilder.Entity("TejaFlow.Domain.Entities.PagoVenta", b =>
                {
                    b.Property<int>("IdPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_pago");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPago"));

                    b.Property<string>("EstadoPago")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("estado_pago");

                    b.Property<DateTime>("FechaPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_pago")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("IdPedido")
                        .HasColumnType("int")
                        .HasColumnName("id_pedido");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("metodo_pago");

                    b.Property<decimal>("Monto")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("monto");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("referencia");

                    b.HasKey("IdPago");

                    b.HasIndex("IdPedido");

                    b.HasIndex("MetodoPago");

                    b.ToTable("PAGO_VENTA", null, t =>
                        {
                            t.HasCheckConstraint("CK_PAGO_ESTADO", "estado_pago IN ('Pendiente', 'Pagado', 'Rechazado', 'Reembolsado')");

                            t.HasCheckConstraint("CK_PAGO_METODO", "metodo_pago IN ('Efectivo', 'TarjetaCredito', 'TarjetaDebito')");

                            t.HasCheckConstraint("CK_PAGO_MONTO", "monto > 0");
                        });

                    b.HasData(
                        new
                        {
                            IdPago = 1,
                            EstadoPago = "Pagado",
                            FechaPago = new DateTime(2026, 2, 15, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            IdPedido = 1,
                            MetodoPago = "TarjetaDebito",
                            Monto = 46713.40m,
                            Referencia = "SEED-PAGO-0001"
                        });
                });

            modelBuilder.Entity("TejaFlow.Domain.Entities.PedidoVenta", b =>
                {
                    b.Property<int>("IdPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_pedido");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPedido"));

                    b.Property<decimal>("CostoFlete")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("costo_flete");

                    b.Property<string>("EstadoPedido")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("estado_pedido");

                    b.Property<DateTime>("FechaPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_pedido")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<decimal>("ImpuestoIva")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("impuesto_iva");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("Total")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("total");

                    b.HasKey("IdPedido");

                    b.HasIndex("EstadoPedido");

                    b.HasIndex("FechaPedido");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdUsuario");

                    b.ToTable("PEDIDO_VENTA", null, t =>
                        {
                            t.HasCheckConstraint("CK_PEDIDO_ESTADO", "estado_pedido IN ('Cotizacion', 'Pagado', 'Parcial', 'Despachado', 'Cancelado')");

                            t.HasCheckConstraint("CK_PEDIDO_IMPORTES", "subtotal >= 0 AND impuesto_iva >= 0 AND costo_flete >= 0 AND total >= 0");
                        });

                    b.HasData(
                        new
                        {
                            IdPedido = 1,
                            CostoFlete = 2500.00m,
                            EstadoPedido = "Pagado",
                            FechaPedido = new DateTime(2026, 2, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IdCliente = 1,
                            IdUsuario = 2,
                            ImpuestoIva = 6098.40m,
                            Subtotal = 38115.00m,
                            Total = 46713.40m
                        });
                });

            modelBuilder.Entity("TejaFlow.Domain.Entities.ProductoTeja", b =>
                {
                    b.Property<int>("IdTeja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_teja");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTeja"));

                    b.Property<decimal>("AnchoCm")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("ancho_cm");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("color");

                    b.Property<decimal>("LongitudCm")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("longitud_cm");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("material");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("modelo");

                    b.Property<decimal>("PesoKg")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("peso_kg");

                    b.Property<decimal>("PrecioBase")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precio_base");

                    b.Property<int>("StockGlobal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("stock_global");

                    b.Property<int>("StockMinimo")
                        .HasColumnType("int")
                        .HasColumnName("stock_minimo_alerta");

                    b.HasKey("IdTeja");

                    b.HasIndex("Material", "Color");

                    b.ToTable("PRODUCTO_TEJA", null, t =>
                        {
                            t.HasCheckConstraint("CK_PRODUCTO_TEJA_DIMENSIONES", "longitud_cm > 0 AND ancho_cm > 0 AND peso_kg > 0");

                            t.HasCheckConstraint("CK_PRODUCTO_TEJA_PRECIO", "precio_base >= 0");

                            t.HasCheckConstraint("CK_PRODUCTO_TEJA_STOCK_GLOBAL", "stock_global >= 0");
                        });

                    b.HasData(
                        new
                        {
                            IdTeja = 1,
                            AnchoCm = 25.00m,
                            Color = "Terracota",
                            LongitudCm = 42.00m,
                            Material = "Barro",
                            Modelo = "Colonial",
                            PesoKg = 2.50m,
                            PrecioBase = 22.50m,
                            StockGlobal = 8000,
                            StockMinimo = 1500
                        },
                        new
                        {
                            IdTeja = 2,
                            AnchoCm = 24.00m,
                            Color = "Grafito",
                            LongitudCm = 40.00m,
                            Material = "Concreto",
                            Modelo = "Francesa",
                            PesoKg = 3.10m,
                            PrecioBase = 25.90m,
                            StockGlobal = 4500,
                            StockMinimo = 1000
                        },
                        new
                        {
                            IdTeja = 3,
                            AnchoCm = 28.00m,
                            Color = "Arena",
                            LongitudCm = 44.00m,
                            Material = "Fibrocemento",
                            Modelo = "Plana Solar",
                            PesoKg = 2.20m,
                            PrecioBase = 31.75m,
                            StockGlobal = 2200,
                            StockMinimo = 800
                        });
                });

            modelBuilder.Entity("TejaFlow.Domain.Entities.RemisionParcial", b =>
                {
                    b.Property<int>("IdRemision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_remision");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRemision"));

                    b.Property<int>("CantidadEnviada")
                        .HasColumnType("int")
                        .HasColumnName("cantidad_entregada_lote");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_registro")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("FirmaRecibido")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("firma_recibido");

                    b.Property<int>("IdDespacho")
                        .HasColumnType("int")
                        .HasColumnName("id_despacho");

                    b.Property<int>("IdDetallePedido")
                        .HasColumnType("int")
                        .HasColumnName("id_detalle_pedido");

                    b.HasKey("IdRemision");

                    b.HasIndex("IdDespacho");

                    b.HasIndex("IdDetallePedido");

                    b.ToTable("REMISION_PARCIAL", null, t =>
                        {
                            t.HasCheckConstraint("CK_REMISION_CANTIDAD", "cantidad_entregada_lote > 0");
                        });
                });

            modelBuilder.Entity("TejaFlow.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_registro")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("rol");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("USUARIO", null, t =>
                        {
                            t.HasCheckConstraint("CK_USUARIO_ROL", "rol IN ('Admin', 'Vendedor', 'Almacenista', 'Logistica', 'Chofer')");
                        });

                    b.HasData(
                        new
                        {
                            IdUsuario = 1,
                            Activo = true,
                            Email = "admin@tejaflow.test",
                            FechaRegistro = new DateTime(2026, 1, 10, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Ana Administradora",
                            PasswordHash = "seed-password-hash-admin",
                            Rol = "Admin"
                        },
                        new
                        {
                            IdUsuario = 2,
                            Activo = true,
                            Email = "ventas@tejaflow.test",
                            FechaRegistro = new DateTime(2026, 1, 10, 8, 5, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Victor Vendedor",
                            PasswordHash = "seed-password-hash-ventas",
                            Rol = "Vendedor"
                        },
                        new
                        {
                            IdUsuario = 3,
                            Activo = true,
                            Email = "almacen@tejaflow.test",
                            FechaRegistro = new DateTime(2026, 1, 10, 8, 10, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Alma Almacenista",
                            PasswordHash = "seed-password-hash-almacen",
                            Rol = "Almacenista"
                        });
                });

            modelBuilder.Entity("TejaFlow.Domain.Entities.DespachoFlete", b =>
                {
                    b.HasOne("TejaFlow.Domain.Entities.PedidoVenta", "Pedido")
                        .WithMany("Despachos")
                        .HasForeignKey("IdPedido")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TejaFlow.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Despachos")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TejaFlow.Domain.Entities.DetallePedido", b =>
                {
                    b.HasOne("TejaFlow.Domain.Entities.PedidoVenta", "Pedido")
                        .WithMany("Detalles")
                        .HasForeignKey("IdPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TejaFlow.Domain.Entities.ProductoTeja", "Teja")
                        .WithMany("DetallesPedido")
                        .HasForeignKey("IdTeja")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Teja");
                });

            modelBuilder.Entity("TejaFlow.Domain.Entities.LoteProduccion", b =>
                {
                    b.HasOne("TejaFlow.Domain.Entities.ProductoTeja", "Teja")
                        .WithMany("Lotes")
                        .HasForeignKey("IdTeja")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Teja");
                });

            modelBuilder.Entity("TejaFlow.Domain.Entities.MermaRotura", b =>
                {
                    b.HasOne("TejaFlow.Domain.Entities.LoteProduccion", "Lote")
                        .WithMany("Mermas")
                        .HasForeignKey("IdLote")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TejaFlow.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Mermas")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lote");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TejaFlow.Domain.Entities.MovimientoInventario", b =>
                {
                    b.HasOne("TejaFlow.Domain.Entities.LoteProduccion", "Lote")
                        .WithMany("Movimientos")
                        .HasForeignKey("IdLote")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TejaFlow.Domain.Entities.MermaRotura", "Merma")
                        .WithMany("Movimientos")
                        .HasForeignKey("IdMerma")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TejaFlow.Domain.Entities.PedidoVenta", "Pedido")
                        .WithMany("Movimientos")
                        .HasForeignKey("IdPedido")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TejaFlow.Domain.Entities.Usuario", "Usuario")
                        .WithMany("MovimientosInventario")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lote");

                    b.Navigation("Merma");

                    b.Navigation("Pedido");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TejaFlow.Domain.Entities.PagoVenta", b =>
                {
                    b.HasOne("TejaFlow.Domain.Entities.PedidoVenta", "Pedido")
                        .WithMany("Pagos")
                        .HasForeignKey("IdPedido")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("TejaFlow.Domain.Entities.PedidoVenta", b =>
                {
                    b.HasOne("TejaFlow.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Pedidos")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TejaFlow.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Pedidos")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TejaFlow.Domain.Entities.RemisionParcial", b =>
                {
                    b.HasOne("TejaFlow.Domain.Entities.DespachoFlete", "Despacho")
                        .WithMany("Remisiones")
                        .HasForeignKey("IdDespacho")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TejaFlow.Domain.Entities.DetallePedido", "DetallePedido")
                        .WithMany("Remisiones")
                        .HasForeignKey("IdDetallePedido")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Despacho");

                    b.Navigation("DetallePedido");
                });

            modelBuilder.Entity("TejaFlow.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("TejaFlow.Domain.Entities.DespachoFlete", b =>
                {
                    b.Navigation("Remisiones");
                });

            modelBuilder.Entity("TejaFlow.Domain.Entities.DetallePedido", b =>
                {
                    b.Navigation("Remisiones");
                });

            modelBuilder.Entity("TejaFlow.Domain.Entities.LoteProduccion", b =>
                {
                    b.Navigation("Mermas");

                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("TejaFlow.Domain.Entities.MermaRotura", b =>
                {
                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("TejaFlow.Domain.Entities.PedidoVenta", b =>
                {
                    b.Navigation("Despachos");

                    b.Navigation("Detalles");

                    b.Navigation("Movimientos");

                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("TejaFlow.Domain.Entities.ProductoTeja", b =>
                {
                    b.Navigation("DetallesPedido");

                    b.Navigation("Lotes");
                });

            modelBuilder.Entity("TejaFlow.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Despachos");

                    b.Navigation("Mermas");

                    b.Navigation("MovimientosInventario");

                    b.Navigation("Pedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
