-- =============================================================================
-- notification-service — esquema relacional (DDL único, MVP)
-- =============================================================================
-- Origen: HU-004 (suscriptor), HU-007 (evento/notificación/envío), kafka-events.md.
-- El esquema "notification" lo crea Flyway (create-schemas=true) o init Compose.
-- PK numéricas (ADR-0002 / R9). evento_id lo aporta el productor (catalog-service).
-- =============================================================================

SET search_path TO notification;

-- Suscriptor a notificaciones por correo (UC-02, data-model §2).
CREATE TABLE suscriptor (
    suscriptor_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(320) NOT NULL,
    estado_suscripcion VARCHAR(32) NOT NULL,
    alta_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    confirmado_en TIMESTAMPTZ,
    baja_en TIMESTAMPTZ,
    CONSTRAINT ck_suscriptor_estado_suscripcion CHECK (estado_suscripcion IN ('ACTIVA', 'CANCELADA'))
);

COMMENT ON TABLE suscriptor IS 'Suscriptor a avisos por correo (UC-02). Estados ACTIVA o CANCELADA según data-model §2.';
COMMENT ON COLUMN suscriptor.email IS 'Correo; unicidad lógica sobre lower(trim(email)) vía índice único.';
COMMENT ON COLUMN suscriptor.estado_suscripcion IS 'ACTIVA o CANCELADA.';
COMMENT ON COLUMN suscriptor.alta_en IS 'Marca temporal de alta del registro.';
COMMENT ON COLUMN suscriptor.confirmado_en IS 'Opcional MVP; puede alinearse a alta_en al crear ACTIVA o permanecer NULL.';
COMMENT ON COLUMN suscriptor.baja_en IS 'Marca temporal de baja/cancelación administrativa.';

CREATE UNIQUE INDEX uq_suscriptor_email_normalizado ON suscriptor (lower(trim(email)));

CREATE INDEX idx_suscriptor_estado_activa ON suscriptor (estado_suscripcion)
    WHERE estado_suscripcion = 'ACTIVA';

-- Evento de catálogo consumido desde Kafka (HU-007). evento_id = id del mensaje (idempotencia).
CREATE TABLE evento_catalogo (
    evento_id BIGINT PRIMARY KEY,
    tipo_evento VARCHAR(64) NOT NULL,
    ejemplar_id BIGINT NOT NULL,
    carga_evento_json TEXT,
    estado_procesamiento VARCHAR(32) NOT NULL,
    recibido_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    procesado_en TIMESTAMPTZ,
    CONSTRAINT ck_evento_catalogo_estado_procesamiento
        CHECK (estado_procesamiento IN ('RECIBIDO', 'PROCESADO')),
    CONSTRAINT ck_evento_catalogo_tipo_evento
        CHECK (tipo_evento IN ('EJEMPLAR_CREADO'))
);

COMMENT ON TABLE evento_catalogo IS 'Hecho de catálogo persistido por notification-service tras consumo (EVENTO_CATALOGO, readme §4.2).';
COMMENT ON COLUMN evento_catalogo.evento_id IS 'Mismo identificador que evento_id en el JSON de catalog.ejemplar.evento (deduplicación).';
COMMENT ON COLUMN evento_catalogo.tipo_evento IS 'Tipo del mensaje Kafka (kafka-events.md); MVP: EJEMPLAR_CREADO.';
COMMENT ON COLUMN evento_catalogo.carga_evento_json IS 'Opcional: copia acotada del payload para trazas; sin PII masiva.';

CREATE TABLE notificacion (
    notificacion_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evento_id BIGINT NOT NULL REFERENCES evento_catalogo (evento_id),
    estado_generacion VARCHAR(32) NOT NULL,
    generada_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_notificacion_estado_generacion
        CHECK (estado_generacion IN ('COMPLETADA', 'SIN_DESTINATARIOS_ACTIVOS'))
);

COMMENT ON TABLE notificacion IS 'Notificación de negocio asociada a un evento de catálogo (readme §4.2). ejemplar_id y tipo_evento vía evento_catalogo (3FN).';

CREATE INDEX idx_notificacion_evento_id ON notificacion (evento_id);

CREATE TABLE envio_notificacion (
    envio_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notificacion_id BIGINT NOT NULL REFERENCES notificacion (notificacion_id),
    suscriptor_id BIGINT NOT NULL REFERENCES suscriptor (suscriptor_id),
    estado_envio VARCHAR(32) NOT NULL,
    generada_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    enviada_en TIMESTAMPTZ,
    mensaje_error VARCHAR(2000),
    CONSTRAINT uq_envio_notificacion_suscriptor UNIQUE (notificacion_id, suscriptor_id),
    CONSTRAINT ck_envio_notificacion_estado_envio
        CHECK (estado_envio IN ('PENDIENTE', 'ENVIADA', 'ERROR'))
);

COMMENT ON TABLE envio_notificacion IS 'Intento de envío por suscriptor (R7, UC-09); estados de SMTP en refinamiento HU-007.';
COMMENT ON COLUMN envio_notificacion.mensaje_error IS 'Detalle técnico acotado; no exponer a clientes HTTP.';

CREATE INDEX idx_envio_notificacion_notificacion_id ON envio_notificacion (notificacion_id);
CREATE INDEX idx_envio_notificacion_suscriptor_id ON envio_notificacion (suscriptor_id);
