SET search_path TO notification;

-- Suscriptor a notificaciones por correo (readme diagrama notification_service, data-model §2, TASK-HU-004-01).
-- PK numéricas (ADR-0002 / R9). Estados ACTIVA | CANCELADA; validación adicional en capa de aplicación.
-- Un único registro por correo normalizado (lower(trim(email))) para el ciclo de vida ACTIVA/CANCELADA.

CREATE TABLE suscriptor (
    suscriptor_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(320) NOT NULL,
    estado_suscripcion VARCHAR(32) NOT NULL,
    alta_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    confirmado_en TIMESTAMPTZ,
    baja_en TIMESTAMPTZ,
    CONSTRAINT ck_suscriptor_estado_suscripcion CHECK (estado_suscripcion IN ('ACTIVA', 'CANCELADA'))
);

COMMENT ON TABLE suscriptor IS 'Suscriptor a avisos por correo (UC-02). Estados ACTIVA o CANCELADA según data-model §2.';

COMMENT ON COLUMN suscriptor.email IS 'Correo; unicidad lógica sobre lower(trim(email)) vía índice único.';
COMMENT ON COLUMN suscriptor.estado_suscripcion IS 'ACTIVA o CANCELADA.';
COMMENT ON COLUMN suscriptor.alta_en IS 'Marca temporal de alta del registro.';
COMMENT ON COLUMN suscriptor.confirmado_en IS 'Opcional MVP; puede alinearse a alta_en al crear ACTIVA o permanecer NULL.';
COMMENT ON COLUMN suscriptor.baja_en IS 'Marca temporal de baja/cancelación administrativa.';

CREATE UNIQUE INDEX uq_suscriptor_email_normalizado ON suscriptor (lower(trim(email)));

CREATE INDEX idx_suscriptor_estado_activa ON suscriptor (estado_suscripcion)
    WHERE estado_suscripcion = 'ACTIVA';
