SET search_path TO notification;

-- Evento de catálogo consumido desde Kafka (HU-007, kafka-events.md). evento_id = id del mensaje (idempotencia).
-- No se usa IDENTITY: el valor lo aporta el productor (catalog-service).

CREATE TABLE evento_catalogo (
    evento_id BIGINT PRIMARY KEY,
    tipo_evento VARCHAR(64) NOT NULL,
    arbol_id BIGINT NOT NULL,
    carga_evento_json TEXT,
    estado_procesamiento VARCHAR(32) NOT NULL,
    recibido_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    procesado_en TIMESTAMPTZ
);

COMMENT ON TABLE evento_catalogo IS 'Hecho de catálogo persistido por notification-service tras consumo (EVENTO_CATALOGO, readme §4.2).';
COMMENT ON COLUMN evento_catalogo.evento_id IS 'Mismo identificador que evento_id en el JSON de catalog.arbol.evento (deduplicación).';
COMMENT ON COLUMN evento_catalogo.carga_evento_json IS 'Opcional: copia acotada del payload para trazas; sin PII masiva.';

CREATE TABLE notificacion (
    notificacion_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evento_id BIGINT NOT NULL REFERENCES evento_catalogo (evento_id),
    arbol_id BIGINT NOT NULL,
    tipo_evento_catalogo VARCHAR(64) NOT NULL,
    estado_generacion VARCHAR(32) NOT NULL,
    generada_en TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE notificacion IS 'Notificación de negocio asociada a un evento de catálogo (readme §4.2).';

CREATE INDEX idx_notificacion_evento_id ON notificacion (evento_id);
CREATE INDEX idx_notificacion_arbol_id ON notificacion (arbol_id);

CREATE TABLE envio_notificacion (
    envio_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notificacion_id BIGINT NOT NULL REFERENCES notificacion (notificacion_id),
    suscriptor_id BIGINT NOT NULL REFERENCES suscriptor (suscriptor_id),
    estado_envio VARCHAR(32) NOT NULL,
    generada_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    enviada_en TIMESTAMPTZ,
    mensaje_error VARCHAR(2000),
    CONSTRAINT uq_envio_notificacion_suscriptor UNIQUE (notificacion_id, suscriptor_id)
);

COMMENT ON TABLE envio_notificacion IS 'Intento de envío por suscriptor (R7, UC-09); estados de SMTP en refinamiento HU-007.';
COMMENT ON COLUMN envio_notificacion.mensaje_error IS 'Detalle técnico acotado; no exponer a clientes HTTP.';

CREATE INDEX idx_envio_notificacion_notificacion_id ON envio_notificacion (notificacion_id);
CREATE INDEX idx_envio_notificacion_suscriptor_id ON envio_notificacion (suscriptor_id);
