version: '3.8'

services:
  postgres:
    container_name: cartera_db
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: ${DB_NAME:-cartera_db}
      POSTGRES_USER: ${DB_USER:-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-admin123}
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=es_CO.UTF-8 --lc-ctype=es_CO.UTF-8"
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
      - ./database/config/postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - "${DB_PORT:-5432}:5432"
    networks:
      - cartera_network
    restart: unless-stopped

  pgadmin:
    container_name: cartera_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin123}
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    depends_on:
      - postgres
    networks:
      - cartera_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  cartera_network:
    driver: bridge 