export type CanonicalGenre =
  | 'Fantasía'
  | 'Thriller'
  | 'Ciencia ficción'
  | 'Romance'
  | 'Histórica'
  | 'Ficción'
  | 'No ficción';

export const GENRE_NORMALIZATION_MAP: Record<CanonicalGenre, string[]> = {
  'Fantasía': [
    'fantasy',
    'fantasy fiction',
    'high fantasy',
    'epic fantasy',
    'magic',
    'magic and supernatural',
    'supernatural',
    'sword and sorcery',
    'witches',
    'vampires',
    'fantasia',
    'fantasía',
    'dragones',
    'mazmorras',
  ],
  Thriller: [
    'thriller',
    'suspense',
    'crime fiction',
    'mystery thriller',
    'psychological thriller',
    'detective',
    'misterio',
    'mystery',
    'horror',
    'terror',
    'suspenso',
    'crime',
    'true crime',
    'domestic thriller',
  ],
  'Ciencia ficción': [
    'science fiction',
    'sci-fi',
    'scifi',
    'dystopia',
    'dystopian',
    'space opera',
    'cyberpunk',
    'ciencia ficcion',
    'ciencia ficción',
    'human cloning',
    'space travel',
    'colonization',
    'apocalyptic',
    'post-apocalyptic',
  ],
  Romance: [
    'romance',
    'love stories',
    'romantic fiction',
    'amor',
    'romantica',
    'romántica',
    'novela romantica',
    'novela romántica',
    'fiction, romance',
    'paranormal romance',
    'dark romance',
    'contemporary romance',
    'romcom',
  ],
  'Histórica': [
    'historical fiction',
    'historical',
    'historical novel',
    'historia ficcion',
    'historia ficción',
    'medieval',
    'war fiction',
  ],
  'Ficción': [
    'fiction',
    'literary fiction',
    'novel',
    'novela',
    'general fiction',
    'contemporary fiction',
    'literature',
    'literatura',
    'young adult',
    'young adult fiction',
    'new adult',
    'juvenile fiction',
    'coming of age',
    'family life fiction',
    'women fiction',
    'psychological fiction',
  ],
  'No ficción': [
    'non-fiction',
    'nonfiction',
    'biography',
    'memoir',
    'essay',
    'self-help',
    'history',
    'science',
    'political science',
    'nuclear war',
    'guerra nuclear',
    'true story',
    'autobiography',
    'current affairs',
  ],
};
