require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'coverage/**/*'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'
    - 'config/**/*.rb'

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

Rails:
  Enabled: true

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Max: 8

RSpec/NestedGroups:
  Max: 4
