-- =============================================================================
-- media-service — esquema relacional (DDL único, MVP)
-- =============================================================================
-- Origen: HU-006 (metadatos de fotografía), HU-014 (categoría PUBLIC/PRIVATE).
-- El esquema "media" lo crea Flyway (create-schemas=true) o init Compose.
-- Sin FK a catalog.ejemplar: referencia lógica por ejemplar_id entre bounded contexts.
-- Borrado MVP: físico (DELETE fila + objeto en bucket); sin soft delete.
-- =============================================================================

SET search_path TO media;

CREATE TABLE fotografia (
    fotografia_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ejemplar_id BIGINT NOT NULL,
    bucket_almacenamiento VARCHAR(128) NOT NULL,
    clave_objeto VARCHAR(512) NOT NULL,
    nombre_fichero_original VARCHAR(255) NOT NULL,
    tipo_mime VARCHAR(64) NOT NULL,
    tamano_bytes BIGINT NOT NULL,
    checksum_sha256 VARCHAR(128),
    ancho_px INTEGER,
    alto_px INTEGER,
    orden INTEGER NOT NULL,
    es_principal BOOLEAN NOT NULL DEFAULT FALSE,
    categoria VARCHAR(16) NOT NULL DEFAULT 'PUBLIC',
    subida_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    subida_por BIGINT NOT NULL,
    CONSTRAINT ck_fotografia_tamano_bytes_positivo CHECK (tamano_bytes > 0),
    CONSTRAINT ck_fotografia_orden_no_negativo CHECK (orden >= 0),
    CONSTRAINT ck_fotografia_mime_no_vacio CHECK (length(trim(tipo_mime)) > 0),
    CONSTRAINT ck_fotografia_categoria CHECK (categoria IN ('PUBLIC', 'PRIVATE')),
    CONSTRAINT uq_fotografia_objeto UNIQUE (bucket_almacenamiento, clave_objeto)
);

CREATE INDEX idx_fotografia_ejemplar_id ON fotografia (ejemplar_id);
CREATE INDEX idx_fotografia_subida_por ON fotografia (subida_por);
CREATE INDEX idx_fotografia_subida_en ON fotografia (subida_en);

CREATE INDEX idx_fotografia_ejemplar_categoria_orden
    ON fotografia (ejemplar_id, categoria, orden);

-- Una única foto principal por ejemplar.
CREATE UNIQUE INDEX uq_fotografia_principal_por_ejemplar
    ON fotografia (ejemplar_id)
    WHERE es_principal = TRUE;
