SET search_path TO media;

-- Modelo relacional mínimo del media-service para HU-006 (subida de fotografías):
-- metadatos por fotografía asociados lógicamente a arbol_id (sin FK entre esquemas/servicios).
CREATE TABLE fotografia (
    fotografia_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    arbol_id BIGINT NOT NULL,
    bucket_almacenamiento VARCHAR(128) NOT NULL,
    clave_objeto VARCHAR(512) NOT NULL,
    nombre_fichero_original VARCHAR(255) NOT NULL,
    tipo_mime VARCHAR(64) NOT NULL,
    tamano_bytes BIGINT NOT NULL,
    checksum_sha256 VARCHAR(128),
    ancho_px INTEGER,
    alto_px INTEGER,
    orden INTEGER NOT NULL,
    es_principal BOOLEAN NOT NULL DEFAULT FALSE,
    subida_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    subida_por BIGINT NOT NULL,
    eliminado_en TIMESTAMPTZ,
    eliminada_por BIGINT,
    CONSTRAINT ck_fotografia_tamano_bytes_positivo CHECK (tamano_bytes > 0),
    CONSTRAINT ck_fotografia_orden_no_negativo CHECK (orden >= 0),
    CONSTRAINT ck_fotografia_mime_no_vacio CHECK (length(trim(tipo_mime)) > 0),
    CONSTRAINT uq_fotografia_objeto UNIQUE (bucket_almacenamiento, clave_objeto)
);

CREATE INDEX idx_fotografia_arbol_id ON fotografia (arbol_id);
CREATE INDEX idx_fotografia_subida_por ON fotografia (subida_por);
CREATE INDEX idx_fotografia_subida_en ON fotografia (subida_en);

-- Una única foto principal activa por árbol.
CREATE UNIQUE INDEX uq_fotografia_principal_activa_por_arbol
    ON fotografia (arbol_id)
    WHERE es_principal = TRUE AND eliminado_en IS NULL;
