# Generated by Django 5.2.8 on 2025-11-12 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description_basic", models.TextField(blank=True)),
                ("description_detailed", models.TextField(blank=True)),
                (
                    "min_players",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "max_players",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "play_time",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Estimated play time in minutes",
                        null=True,
                    ),
                ),
                ("min_age", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("category", models.CharField(blank=True, max_length=120)),
                ("rules_basic", models.TextField(blank=True)),
                ("rules_detailed", models.TextField(blank=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="games/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RuleSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("basic", "basic"),
                            ("detailed", "detailed"),
                            ("quickstart", "quickstart"),
                            ("advanced", "advanced"),
                        ],
                        default="basic",
                        max_length=20,
                    ),
                ),
                ("language", models.CharField(default="es", max_length=2)),
                ("version", models.CharField(blank=True, max_length=32)),
                ("source", models.CharField(blank=True, max_length=120)),
                ("content_markdown", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rulesets",
                        to="catalog.game",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RuleVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("description_markdown", models.TextField(blank=True)),
                ("is_official", models.BooleanField(default=False)),
                (
                    "tags",
                    models.CharField(
                        blank=True, help_text="Comma separated tags", max_length=255
                    ),
                ),
                ("min_players_delta", models.IntegerField(blank=True, null=True)),
                ("max_players_delta", models.IntegerField(blank=True, null=True)),
                ("play_time_delta", models.IntegerField(blank=True, null=True)),
                ("min_age_delta", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ruleset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="catalog.ruleset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrainingVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("url", models.URLField()),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("youtube", "YouTube"),
                            ("vimeo", "Vimeo"),
                            ("other", "Other"),
                        ],
                        default="youtube",
                        max_length=20,
                    ),
                ),
                ("language", models.CharField(default="es", max_length=2)),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("is_official", models.BooleanField(default=False)),
                (
                    "quality_rating",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="catalog.game",
                    ),
                ),
                (
                    "ruleset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="videos",
                        to="catalog.ruleset",
                    ),
                ),
            ],
        ),
    ]
