# Generated by Django 5.2.8 on 2025-11-12 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "slug",
                    models.SlugField(
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "name_es",
                    models.CharField(max_length=100, verbose_name="Nombre (Español)"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=100, verbose_name="Nombre (English)"),
                ),
                (
                    "name_fr",
                    models.CharField(max_length=100, verbose_name="Nombre (Français)"),
                ),
                (
                    "description_es",
                    models.TextField(blank=True, verbose_name="Descripción (Español)"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, verbose_name="Descripción (English)"),
                ),
                (
                    "description_fr",
                    models.TextField(blank=True, verbose_name="Descripción (Français)"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Emoji o código de icono", max_length=50
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Categoría",
                "verbose_name_plural": "Categorías",
                "ordering": ["name_es"],
            },
        ),
        migrations.AlterModelOptions(
            name="game",
            options={
                "ordering": ["name"],
                "verbose_name": "Juego",
                "verbose_name_plural": "Juegos",
            },
        ),
        migrations.AddField(
            model_name="game",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Activo"),
        ),
        migrations.AddField(
            model_name="game",
            name="publisher",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Editorial"
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name="game",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="game",
            name="year_published",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Año de publicación"
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="category",
            field=models.CharField(
                blank=True, help_text="Deprecated: Use categories field", max_length=120
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="description_basic",
            field=models.TextField(blank=True, verbose_name="Descripción básica"),
        ),
        migrations.AlterField(
            model_name="game",
            name="description_detailed",
            field=models.TextField(blank=True, verbose_name="Descripción detallada"),
        ),
        migrations.AlterField(
            model_name="game",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="games/", verbose_name="Imagen"
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="max_players",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Jugadores máximos"
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="min_age",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Edad mínima"
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="min_players",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Jugadores mínimos"
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="game",
            name="play_time",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Tiempo estimado de juego en minutos",
                null=True,
                verbose_name="Tiempo de juego",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="rules_basic",
            field=models.TextField(blank=True, verbose_name="Reglas básicas"),
        ),
        migrations.AlterField(
            model_name="game",
            name="rules_detailed",
            field=models.TextField(blank=True, verbose_name="Reglas detalladas"),
        ),
        migrations.AddField(
            model_name="game",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="games",
                to="catalog.category",
                verbose_name="Categorías",
            ),
        ),
    ]
