# Generated by Django 5.2.8 on 2025-11-12 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_category_alter_game_options_game_is_active_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="game",
            options={
                "ordering": ["name_es"],
                "verbose_name": "Juego",
                "verbose_name_plural": "Juegos",
            },
        ),
        migrations.RemoveField(
            model_name="game",
            name="description_basic",
        ),
        migrations.RemoveField(
            model_name="game",
            name="description_detailed",
        ),
        migrations.RemoveField(
            model_name="game",
            name="name",
        ),
        migrations.RemoveField(
            model_name="game",
            name="play_time",
        ),
        migrations.RemoveField(
            model_name="game",
            name="rules_basic",
        ),
        migrations.RemoveField(
            model_name="game",
            name="rules_detailed",
        ),
        migrations.AddField(
            model_name="game",
            name="description_en",
            field=models.TextField(blank=True, verbose_name="Descripción (English)"),
        ),
        migrations.AddField(
            model_name="game",
            name="description_es",
            field=models.TextField(blank=True, verbose_name="Descripción (Español)"),
        ),
        migrations.AddField(
            model_name="game",
            name="description_fr",
            field=models.TextField(blank=True, verbose_name="Descripción (Français)"),
        ),
        migrations.AddField(
            model_name="game",
            name="difficulty",
            field=models.CharField(
                blank=True,
                choices=[
                    ("easy", "Fácil"),
                    ("medium", "Media"),
                    ("hard", "Difícil"),
                    ("expert", "Experto"),
                ],
                max_length=20,
                verbose_name="Dificultad",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="max_playtime",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Tiempo máximo (minutos)"
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="min_playtime",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Tiempo mínimo (minutos)"
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Nombre (English)"
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="name_es",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Nombre (Español)"
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="name_fr",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Nombre (Français)"
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="rules_url",
            field=models.URLField(blank=True, verbose_name="URL de reglas (PDF)"),
        ),
    ]
