# Generated by Django 5.2.8 on 2025-11-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_game_options_remove_game_description_basic_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="name_en",
            field=models.CharField(
                default="new", max_length=255, verbose_name="Nombre (English)"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="game",
            name="name_es",
            field=models.CharField(
                default="new", max_length=255, verbose_name="Nombre (Español)"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="game",
            name="name_fr",
            field=models.CharField(
                default="new", max_length=255, verbose_name="Nombre (Français)"
            ),
            preserve_default=False,
        ),
    ]
