apiVersion: v1
kind: Service
metadata:
  name: aura-mailhog
  labels:
    app: aura-mailhog
spec:
  selector:
    app: aura-mailhog
  ports:
    - name: smtp
      port: 1025
      targetPort: 1025
    - name: web
      port: 8025
      targetPort: 8025
