-- Rollback para migración CreateDoctorSpecialtiesTable
-- Ejecutar solo si es necesario revertir manualmente
-- Fecha: 2026-01-20
-- Migración: 1769058001000-CreateDoctorSpecialtiesTable

-- Eliminar foreign keys
ALTER TABLE DOCTOR_SPECIALTIES DROP FOREIGN KEY IF EXISTS FK_DOCTOR_SPECIALTIES_DOCTOR_ID;
ALTER TABLE DOCTOR_SPECIALTIES DROP FOREIGN KEY IF EXISTS FK_DOCTOR_SPECIALTIES_SPECIALTY_ID;

-- Eliminar índices
DROP INDEX IF EXISTS IDX_DOCTOR_SPECIALTIES_IS_PRIMARY ON DOCTOR_SPECIALTIES;
DROP INDEX IF EXISTS IDX_DOCTOR_SPECIALTIES_SPECIALTY_ID ON DOCTOR_SPECIALTIES;
DROP INDEX IF EXISTS IDX_DOCTOR_SPECIALTIES_DOCTOR_ID ON DOCTOR_SPECIALTIES;

-- Eliminar tabla
DROP TABLE IF EXISTS DOCTOR_SPECIALTIES;
