-- Rollback para migración CreateDoctorsTable
-- Ejecutar solo si es necesario revertir manualmente
-- Fecha: 2026-01-20
-- Migración: 1769057119000-CreateDoctorsTable

-- Eliminar foreign keys
ALTER TABLE DOCTORS DROP FOREIGN KEY IF EXISTS FK_DOCTORS_USER_ID;

-- Eliminar índices
DROP INDEX IF EXISTS IDX_DOCTORS_USER_ID ON DOCTORS;
DROP INDEX IF EXISTS IDX_DOCTORS_LOCATION ON DOCTORS;
DROP INDEX IF EXISTS IDX_DOCTORS_POSTAL_CODE ON DOCTORS;
DROP INDEX IF EXISTS IDX_DOCTORS_VERIFICATION_STATUS ON DOCTORS;

-- Eliminar tabla
DROP TABLE IF EXISTS DOCTORS;
