/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SharingRouteImport } from './routes/sharing'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RecipesRouteImport } from './routes/recipes'
import { Route as PantryRouteImport } from './routes/pantry'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AddRouteImport } from './routes/add'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ItemIdRouteImport } from './routes/item.$id'
import { Route as AddManualRouteImport } from './routes/add.manual'

const SharingRoute = SharingRouteImport.update({
  id: '/sharing',
  path: '/sharing',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRoute = RecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const PantryRoute = PantryRouteImport.update({
  id: '/pantry',
  path: '/pantry',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AddRoute = AddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemIdRoute = ItemIdRouteImport.update({
  id: '/item/$id',
  path: '/item/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AddManualRoute = AddManualRouteImport.update({
  id: '/manual',
  path: '/manual',
  getParentRoute: () => AddRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add': typeof AddRouteWithChildren
  '/auth': typeof AuthRoute
  '/insights': typeof InsightsRoute
  '/pantry': typeof PantryRoute
  '/recipes': typeof RecipesRoute
  '/settings': typeof SettingsRoute
  '/sharing': typeof SharingRoute
  '/add/manual': typeof AddManualRoute
  '/item/$id': typeof ItemIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add': typeof AddRouteWithChildren
  '/auth': typeof AuthRoute
  '/insights': typeof InsightsRoute
  '/pantry': typeof PantryRoute
  '/recipes': typeof RecipesRoute
  '/settings': typeof SettingsRoute
  '/sharing': typeof SharingRoute
  '/add/manual': typeof AddManualRoute
  '/item/$id': typeof ItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add': typeof AddRouteWithChildren
  '/auth': typeof AuthRoute
  '/insights': typeof InsightsRoute
  '/pantry': typeof PantryRoute
  '/recipes': typeof RecipesRoute
  '/settings': typeof SettingsRoute
  '/sharing': typeof SharingRoute
  '/add/manual': typeof AddManualRoute
  '/item/$id': typeof ItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add'
    | '/auth'
    | '/insights'
    | '/pantry'
    | '/recipes'
    | '/settings'
    | '/sharing'
    | '/add/manual'
    | '/item/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add'
    | '/auth'
    | '/insights'
    | '/pantry'
    | '/recipes'
    | '/settings'
    | '/sharing'
    | '/add/manual'
    | '/item/$id'
  id:
    | '__root__'
    | '/'
    | '/add'
    | '/auth'
    | '/insights'
    | '/pantry'
    | '/recipes'
    | '/settings'
    | '/sharing'
    | '/add/manual'
    | '/item/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddRoute: typeof AddRouteWithChildren
  AuthRoute: typeof AuthRoute
  InsightsRoute: typeof InsightsRoute
  PantryRoute: typeof PantryRoute
  RecipesRoute: typeof RecipesRoute
  SettingsRoute: typeof SettingsRoute
  SharingRoute: typeof SharingRoute
  ItemIdRoute: typeof ItemIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sharing': {
      id: '/sharing'
      path: '/sharing'
      fullPath: '/sharing'
      preLoaderRoute: typeof SharingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes': {
      id: '/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof RecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pantry': {
      id: '/pantry'
      path: '/pantry'
      fullPath: '/pantry'
      preLoaderRoute: typeof PantryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/item/$id': {
      id: '/item/$id'
      path: '/item/$id'
      fullPath: '/item/$id'
      preLoaderRoute: typeof ItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add/manual': {
      id: '/add/manual'
      path: '/manual'
      fullPath: '/add/manual'
      preLoaderRoute: typeof AddManualRouteImport
      parentRoute: typeof AddRoute
    }
  }
}

interface AddRouteChildren {
  AddManualRoute: typeof AddManualRoute
}

const AddRouteChildren: AddRouteChildren = {
  AddManualRoute: AddManualRoute,
}

const AddRouteWithChildren = AddRoute._addFileChildren(AddRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddRoute: AddRouteWithChildren,
  AuthRoute: AuthRoute,
  InsightsRoute: InsightsRoute,
  PantryRoute: PantryRoute,
  RecipesRoute: RecipesRoute,
  SettingsRoute: SettingsRoute,
  SharingRoute: SharingRoute,
  ItemIdRoute: ItemIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
