/**
 * useMeditationList Hook
 * 
 * React Query hook for fetching user's meditation list.
 * 
 * Features:
 * - Auto-fetches on mount
 * - Caching with React Query
 * - Loading and error states
 * - Auto-refetch on window focus
 * - Type-safe with generated OpenAPI client
 * 
 * Server-State Management: React Query (NOT Zustand)
 */

import { useQuery } from '@tanstack/react-query';
import { Configuration, PlaybackApi, MeditationItem } from '../../api/generated/playback/src';

/**
 * API Configuration
 * TODO: Replace with actual auth token from authentication context (US1)
 */
const getApiConfig = (): Configuration => {
  return new Configuration({
    basePath: import.meta.env.VITE_API_BASE_URL || 'http://localhost:8080/api/v1',
    headers: {
      // Temporary: X-User-Id header until US1 implements JWT
      'X-User-Id': import.meta.env.VITE_USER_ID || '550e8400-e29b-41d4-a716-446655440000'
    }
  });
};

/**
 * Fetches list of meditations from backend.
 * Uses autogenerated PlaybackApi client.
 */
const fetchMeditationList = async (): Promise<MeditationItem[]> => {
  const api = new PlaybackApi(getApiConfig());
  
  try {
    const response = await api.listUserMeditations({});
    return response.meditations || [];
  } catch (error) {
    console.error('Error fetching meditation list:', error);
    throw new Error('Could not load the meditation list');
  }
};

/**
 * useMeditationList Hook
 * 
 * Fetches and manages meditation list state using React Query.
 * 
 * @returns {object} React Query result with:
 *   - data: MeditationItem[] (meditation list)
 *   - isLoading: boolean
 *   - error: Error | null
 *   - refetch: () => void
 * 
 * @example
 * ```tsx
 * function MyComponent() {
 *   const { data: meditations, isLoading, error } = useMeditationList();
 *   
 *   if (isLoading) return <p>Loading...</p>;
 *   if (error) return <p>Error: {error.message}</p>;
 *   
 *   return <MeditationList meditations={meditations} />;
 * }
 * ```
 */
export const useMeditationList = () => {
  return useQuery({
    queryKey: ['meditations', 'list'],
    queryFn: fetchMeditationList,
    staleTime: 1000 * 60 * 5, // 5 minutes
    gcTime: 1000 * 60 * 10,    // 10 minutes (renamed from cacheTime in v5)
    refetchOnWindowFocus: true,
    retry: 2,
    // Convert Error to user-friendly error object
    throwOnError: false
  });
};

export default useMeditationList;
