apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patchesStrategicMerge:
  - patch-resources.yaml
  - patch-replicas.yaml

images:
  - name: aura-api
    newName: ghcr.io/pedrosrp/aura-api
    newTag: latest
  - name: aura-frontend
    newName: ghcr.io/pedrosrp/aura-frontend
    newTag: latest
  - name: aura-worker-email
    newName: ghcr.io/pedrosrp/aura-worker-email
    newTag: latest
  - name: aura-worker-ssg
    newName: ghcr.io/pedrosrp/aura-worker-ssg
    newTag: latest
  - name: aura-worker-whatsapp
    newName: ghcr.io/pedrosrp/aura-worker-whatsapp
    newTag: latest
