# Generated by Django 6.1 on 2026-08-23 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto', models.CharField(max_length=10)),
                ('id_externo', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=150)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('proyecto', 'id_externo'), name='plan_identidad_unica')],
            },
        ),
        migrations.CreateModel(
            name='EmpresaPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_externo', models.CharField(max_length=100)),
                ('tipo_contrato', models.IntegerField(choices=[(1, 'Freemium'), (2, 'Pagado')])),
                ('estatus', models.IntegerField(choices=[(1, 'Vigente'), (4, 'Bloqueado'), (0, 'Expirado')])),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('prorroga', models.PositiveIntegerField(default=0)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ultima_sync', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='empresas.company')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suscripciones', to='financiero.plan')),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='CortePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_externo', models.CharField(max_length=100)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('excedente', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('periodo_inicio', models.DateField()),
                ('periodo_final', models.DateField()),
                ('complemento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cortes', to='financiero.complemento')),
                ('empresa_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cortes', to='financiero.empresaplan')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('empresa_plan', 'id_externo'), name='corte_plan_identidad_unica')],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_externo', models.CharField(max_length=100)),
                ('estatus', models.IntegerField(choices=[(0, 'Eliminado'), (1, 'Pagado'), (2, 'Pendiente'), (3, 'Facturado')])),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('importe_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('impuesto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateField()),
                ('ultima_sync', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='empresas.company')),
                ('empresa_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='financiero.empresaplan')),
            ],
            options={
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['empresa', 'estatus'], name='financiero__empresa_30a81b_idx')],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'id_externo'), name='pago_identidad_unica')],
            },
        ),
        migrations.AddConstraint(
            model_name='empresaplan',
            constraint=models.UniqueConstraint(fields=('empresa', 'id_externo'), name='empresa_plan_identidad_unica'),
        ),
    ]
