# Generated by Django 6.1 on 2026-08-23 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='prorroga',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
