# Generated by Django 6.1 on 2026-08-24 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiero', '0002_plan_prorroga'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresaplan',
            name='origen',
            field=models.CharField(choices=[('erp', 'Sincronizado del ERP'), ('eyemaster', 'Creado en EyeMaster')], default='erp', max_length=20),
        ),
        migrations.AddField(
            model_name='plan',
            name='origen',
            field=models.CharField(choices=[('erp', 'Sincronizado del ERP'), ('eyemaster', 'Creado en EyeMaster')], default='erp', max_length=20),
        ),
        migrations.AddField(
            model_name='plan',
            name='precio_base',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='empresaplan',
            name='id_externo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='id_externo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='proyecto',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='PlanComplemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite', models.DecimalField(decimal_places=2, max_digits=12)),
                ('complemento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planes', to='financiero.complemento')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complementos_plan', to='financiero.plan')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('plan', 'complemento'), name='plan_complemento_unico')],
            },
        ),
    ]
