spring.application.name=notification-service
server.port=8083

spring.mvc.problemdetails.enabled=true
management.endpoints.web.exposure.include=health,info

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} [correlationId=%X{correlationId:-}] - %msg%n
