spring.datasource.url=jdbc:postgresql://localhost:5433/mtl
spring.datasource.username=mtl
spring.datasource.password=mtl_dev_password
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=notification
spring.flyway.schemas=notification
spring.flyway.default-schema=notification
