import type { TranslationResource } from './en';

/** German bundle. Key-aligned with `en` (compiler-enforced). Copy pending native review (R6). */
export const de: TranslationResource = {
  translation: {
    nav: {
      myLessons: 'Meine Lektionen',
      newLesson: 'Neue Lektion',
      settings: 'Einstellungen',
      lesson: 'Lektion',
      study: 'Lernen',
      results: 'Ergebnisse',
      logIn: 'Anmelden',
      signUp: 'Registrieren',
    },
    home: {
      savedLessons: 'Gespeicherte Lektionen',
      openDemo: 'Demo-Lektion öffnen',
    },
    lessons: {
      count_one: '{{count}} Lektion',
      count_other: '{{count}} Lektionen',
    },
    upload: {
      intro: 'Lade ein PDF hoch, um eine Lektion zu erstellen',
      apiKeyRequired: {
        message: 'Ein API-Schlüssel ist erforderlich, um Lektionen zu erstellen.',
        action: 'API-Schlüssel hinzufügen',
      },
    },
    lesson: {
      title: 'Lektion {{id}}',
      start: 'Lernen beginnen',
      viewResults: 'Ergebnisse ansehen',
    },
    player: {
      intro: 'Folien-Player für Lektion {{id}}',
      finish: 'Lektion abschließen',
    },
    results: {
      score: '{{correct}} / {{total}}',
      scorePercent: '{{percent}}%',
      scoreAnnouncement: '{{score}}, {{percent}}',
      retake: 'Aktivitäten wiederholen',
      backHome: 'Zurück zu meinen Lektionen',
      completeHeadline: 'Lektion abgeschlossen',
      completeBody: 'Du hast das Ende dieser Lektion erreicht.',
      saveFailed: 'Dieser Versuch konnte nicht gespeichert werden',
      retrySave: 'Erneut versuchen',
    },
    auth: {
      email: 'E-Mail',
      password: 'Passwort',
      submit: 'Anmelden',
      signingIn: 'Anmeldung läuft…',
      toSignUp: 'Kein Konto? Registrieren',
      toLogIn: 'Schon ein Konto? Anmelden',
      logOut: 'Abmelden',
      logOutConfirmHeadline: 'Abmelden?',
      logOutConfirmBody: 'Du musst dich erneut anmelden, um auf deine Lektionen zuzugreifen.',
      logOutConfirmAction: 'Abmelden',
      logOutCancelAction: 'Abbrechen',
      error: {
        email: 'Bitte gib eine gültige E-Mail-Adresse ein',
        invalidCredentials: 'E-Mail oder Passwort ungültig',
        network: 'Netzwerkfehler',
      },
    },
    settings: {
      title: 'Einstellungen',
      language: {
        heading: 'Sprache',
        a11yLabel: 'Sprache auswählen',
      },
      apiKey: {
        inputLabel: 'API-Schlüssel',
        save: 'Speichern',
        saving: 'Wird gespeichert…',
        loadingStatus: 'Status deines API-Schlüssels wird geprüft…',
        replace: 'Ersetzen',
        remove: 'Entfernen',
        savedStatus: '{{provider}}-Schlüssel gespeichert · Aktualisiert {{date}}',
        guidance: 'Noch keinen Schlüssel? Bei OpenAI erhalten',
        removeConfirmHeadline: 'API-Schlüssel entfernen?',
        removeConfirmBody: 'Du musst einen neuen Schlüssel hinzufügen, um wieder Lektionen zu erstellen.',
        removeConfirmAction: 'Entfernen bestätigen',
        removeConfirmCancelAction: 'Abbrechen',
        error: {
          invalidKey: 'Dieser Schlüssel konnte nicht validiert werden. Bitte prüfen und erneut versuchen.',
          network: 'Server nicht erreichbar. Bitte erneut versuchen.',
          empty: 'Gib deinen API-Schlüssel ein.',
        },
      },
    },
    activity: {
      mcq: {
        correct: 'Richtig',
        incorrect: 'Falsch',
        explanation: 'Erklärung',
        unavailable: 'Diese Frage ist nicht verfügbar',
      },
      matching: {
        submit: 'Absenden',
        correct: 'Alles richtig!',
        incorrect: 'Nicht ganz',
        correctPair: 'richtig',
        incorrectPair: 'falsch',
        explanationHeading: 'Warum',
        summary: '{{correct}} von {{total}} richtig',
        unavailable: 'Diese Aktivität ist nicht verfügbar',
      },
      fillInTheBlank: {
        submit: 'Absenden',
        correct: 'Richtig!',
        incorrect: 'Falsch',
        explanationHeading: 'Warum',
        unavailable: 'Diese Aktivität ist nicht verfügbar',
        blankInput: 'Lücke ausfüllen',
      },
      openEnded: {
        submit: 'Absenden',
        yourAnswer: 'Deine Antwort',
        modelAnswer: 'Musterantwort',
        explanationHeading: 'Warum',
        unavailable: 'Diese Aktivität ist nicht verfügbar',
        answerInput: 'Deine Antwort',
      },
      flashcard: {
        reveal: 'Antwort aufdecken',
        recalled: 'Gewusst',
        notRecalled: 'Nicht gewusst',
        recalledConfirmed: 'Als gewusst markiert',
        notRecalledConfirmed: 'Als nicht gewusst markiert',
        answerHeading: 'Antwort',
        explanationHeading: 'Warum',
        unavailable: 'Diese Aktivität ist nicht verfügbar',
      },
    },
  },
};
