import type { TranslationResource } from './en';

/** Portuguese bundle. Key-aligned with `en` (compiler-enforced). Copy pending native review (R6). */
export const pt: TranslationResource = {
  translation: {
    nav: {
      myLessons: 'Minhas lições',
      newLesson: 'Nova lição',
      settings: 'Configurações',
      lesson: 'Lição',
      study: 'Estudar',
      results: 'Resultados',
      logIn: 'Entrar',
      signUp: 'Cadastrar',
    },
    home: {
      savedLessons: 'Lições salvas',
      openDemo: 'Abrir lição de demonstração',
    },
    lessons: {
      count_one: '{{count}} lição',
      count_other: '{{count}} lições',
    },
    upload: {
      intro: 'Envie um PDF para gerar uma lição',
      apiKeyRequired: {
        message: 'É necessária uma chave de API para gerar lições.',
        action: 'Adicionar chave de API',
      },
    },
    lesson: {
      title: 'Lição {{id}}',
      start: 'Começar a estudar',
      viewResults: 'Ver resultados',
    },
    player: {
      intro: 'Reprodutor de slides da lição {{id}}',
      finish: 'Concluir lição',
    },
    results: {
      score: '{{correct}} / {{total}}',
      scorePercent: '{{percent}}%',
      scoreAnnouncement: '{{score}}, {{percent}}',
      retake: 'Refazer atividades',
      backHome: 'Voltar às minhas lições',
      completeHeadline: 'Lição concluída',
      completeBody: 'Você chegou ao final desta lição.',
      saveFailed: 'Não foi possível salvar esta tentativa',
      retrySave: 'Tentar novamente',
    },
    auth: {
      email: 'E-mail',
      password: 'Senha',
      submit: 'Entrar',
      signingIn: 'Entrando…',
      toSignUp: 'Não tem conta? Cadastre-se',
      toLogIn: 'Já tem conta? Entre',
      logOut: 'Sair',
      logOutConfirmHeadline: 'Sair da conta?',
      logOutConfirmBody: 'Você precisará entrar novamente para acessar suas lições.',
      logOutConfirmAction: 'Sair',
      logOutCancelAction: 'Cancelar',
      error: {
        email: 'Informe um e-mail válido',
        invalidCredentials: 'E-mail ou senha inválidos',
        network: 'Erro de rede',
      },
    },
    settings: {
      title: 'Configurações',
      language: {
        heading: 'Idioma',
        a11yLabel: 'Escolha um idioma',
      },
      apiKey: {
        inputLabel: 'Chave de API',
        save: 'Salvar',
        saving: 'Salvando…',
        loadingStatus: 'Verificando o status da sua chave de API…',
        replace: 'Substituir',
        remove: 'Remover',
        savedStatus: 'Chave da {{provider}} salva · Atualizada em {{date}}',
        guidance: 'Não tem uma chave? Obtenha uma na OpenAI',
        removeConfirmHeadline: 'Remover chave de API?',
        removeConfirmBody: 'Você precisará adicionar uma nova chave para gerar lições novamente.',
        removeConfirmAction: 'Confirmar remoção',
        removeConfirmCancelAction: 'Cancelar',
        error: {
          invalidKey: 'Essa chave não foi validada. Verifique e tente novamente.',
          network: 'Não foi possível conectar ao servidor. Tente novamente.',
          empty: 'Informe sua chave de API.',
        },
      },
    },
    activity: {
      mcq: {
        correct: 'Correto',
        incorrect: 'Incorreto',
        explanation: 'Explicação',
        unavailable: 'Esta pergunta não está disponível',
      },
      matching: {
        submit: 'Enviar',
        correct: 'Tudo correto!',
        incorrect: 'Quase',
        correctPair: 'correto',
        incorrectPair: 'incorreto',
        explanationHeading: 'Por quê',
        summary: '{{correct}} de {{total}} corretos',
        unavailable: 'Esta atividade não está disponível',
      },
      fillInTheBlank: {
        submit: 'Enviar',
        correct: 'Correto!',
        incorrect: 'Incorreto',
        explanationHeading: 'Por quê',
        unavailable: 'Esta atividade não está disponível',
        blankInput: 'Preencha o espaço',
      },
      openEnded: {
        submit: 'Enviar',
        yourAnswer: 'Sua resposta',
        modelAnswer: 'Resposta modelo',
        explanationHeading: 'Por quê',
        unavailable: 'Esta atividade não está disponível',
        answerInput: 'Sua resposta',
      },
      flashcard: {
        reveal: 'Mostrar resposta',
        recalled: 'Lembrei',
        notRecalled: 'Não lembrei',
        recalledConfirmed: 'Marcado como lembrado',
        notRecalledConfirmed: 'Marcado como não lembrado',
        answerHeading: 'Resposta',
        explanationHeading: 'Por quê',
        unavailable: 'Esta atividade não está disponível',
      },
    },
  },
};
