# Generated by Django 6.1 on 2026-08-23 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('empresa-cliente', 'Empresa-Cliente'), ('empresa-grupo', 'Empresa-Grupo'), ('empresa-dist', 'Empresa-Distribuidor'), ('grupo-dist', 'Grupo-Distribuidor')], max_length=20)),
                ('origen_id', models.PositiveIntegerField()),
                ('destino_id', models.PositiveIntegerField()),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('accion', models.CharField(choices=[('asignar', 'Asignar'), ('reasignar', 'Reasignar'), ('remover', 'Remover')], max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['origen_id', 'tipo', '-fecha_inicio'], name='comercial_a_origen__cf9a6b_idx'), models.Index(fields=['usuario'], name='comercial_a_usuario_f44470_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('fecha_fin__isnull', True)), fields=('origen_id', 'tipo'), name='asignacion_vigente_unica'), models.CheckConstraint(condition=models.Q(('fecha_fin__isnull', True), ('fecha_fin__gt', models.F('fecha_inicio')), _connector='OR'), name='asignacion_fecha_fin_posterior')],
            },
        ),
    ]
