export * from './config/i18n';
export * from './config/supported-locales';
export * from './detector/device-locale';
export * from './detector/resolve-initial-locale';
export * from './hooks/use-localization';
export type * from './hooks/use-localization.types';
export { LocalizationProvider } from './provider/localization-provider';
export type * from './provider/localization-provider.types';
export type { TranslationResource } from './resources';
export { resources } from './resources';
