"""initial schema

Revision ID: 5fcc34da2156
Revises: 
Create Date: 2026-07-29 16:25:32.506582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.models.base


# revision identifiers, used by Alembic.
revision: str = '5fcc34da2156'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('sex', sa.String(length=20), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('clinical_baseline',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('patient_id', app.models.base.GUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('concept', sa.String(length=150), nullable=False),
    sa.Column('start_date', sa.String(length=50), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_baseline_patient_id'), 'clinical_baseline', ['patient_id'], unique=False)
    op.create_table('medical_events',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('patient_id', app.models.base.GUID(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('date', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('clinical_summary', sa.Text(), nullable=False),
    sa.Column('original_notes', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('doctor', sa.String(length=100), nullable=True),
    sa.Column('medical_center', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('red_flag', sa.Boolean(), nullable=False),
    sa.Column('alert_justification', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_events_patient_id'), 'medical_events', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medical_events_patient_id'), table_name='medical_events')
    op.drop_table('medical_events')
    op.drop_index(op.f('ix_clinical_baseline_patient_id'), table_name='clinical_baseline')
    op.drop_table('clinical_baseline')
    op.drop_table('patients')
    # ### end Alembic commands ###
