"""Add file retrieval tracking and audit log enhancements for US-006"""

revision = 'e34822ef5117'
down_revision = '0001_initial_models'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    # ### commands auto generated by Alembic - adjusted for compatibility ###
    op.add_column('audit_logs', sa.Column('resource_type', sa.String(length=50), nullable=True))
    op.add_column('audit_logs', sa.Column('resource_id', sa.Integer(), nullable=True))
    op.add_column('audit_logs', sa.Column('ip_address', sa.String(length=45), nullable=True))
    op.add_column('audit_logs', sa.Column('user_agent', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.add_column('files', sa.Column('storage_key', sa.String(length=255), nullable=True))
    op.add_column('files', sa.Column('mime_type', sa.String(length=255), nullable=True))
    op.add_column('files', sa.Column('retrieval_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('files', sa.Column('last_retrieved_at', sa.DateTime(), nullable=True))
    op.add_column('files', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_files_deleted_at'), 'files', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - adjusted for compatibility ###
    op.drop_index(op.f('ix_files_deleted_at'), table_name='files')
    op.drop_column('files', 'deleted_at')
    op.drop_column('files', 'last_retrieved_at')
    op.drop_column('files', 'retrieval_count')
    op.drop_column('files', 'mime_type')
    op.drop_column('files', 'storage_key')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_column('audit_logs', 'user_agent')
    op.drop_column('audit_logs', 'ip_address')
    op.drop_column('audit_logs', 'resource_id')
    op.drop_column('audit_logs', 'resource_type')
    # ### end Alembic commands ###
