-- ai-lesson-generation (Slice 1, task-3) -- get_api_key(): the server-side read counterpart to
-- save_api_key()/remove_api_key() (spec.md Open decision #6). R6 deliberately left the read to
-- this story (ai-key-management/spec.md:45 -- "R2 will trigger its own Edge Function, which
-- reads the key from the same store server-side"). Same security model as the other two RPCs:
-- security definer to reach the vault schema, execute restricted to service_role only -- an
-- authenticated client cannot call this even with a valid JWT (@s7), only indirectly via the
-- generate-lesson Edge Function, which authenticates the caller and supplies p_user_id itself
-- (never a client-supplied id). Never exposes the key to the client contract or logs (@s8) -- it
-- is only ever read inside the function and passed straight to the Vercel AI SDK.
--
-- Same Vault-vs-pgcrypto fallback caveat as R6 (risks.md R5): if hosted Vault is unavailable,
-- swap this migration's `vault.decrypted_secrets` read for the documented pgcrypto/pgsodium
-- bytea fallback -- this function's signature and every higher layer are unaffected either way.
--
-- Reversibility note (down migration is not auto-generated by the CLI): to revert, run
--   drop function if exists public.get_api_key(uuid);

create function public.get_api_key(p_user_id uuid)
returns table (provider text, api_key text)
language plpgsql
security definer
set search_path = public, vault, pg_temp
as $$
begin
  return query
    select uak.provider, vs.decrypted_secret
    from public.user_ai_keys uak
    join vault.decrypted_secrets vs on vs.id = uak.secret_id
    where uak.user_id = p_user_id;
end;
$$;

revoke all on function public.get_api_key(uuid) from public;
grant execute on function public.get_api_key(uuid) to service_role;
