apiVersion: v1
kind: Secret
metadata:
  name: aura-postgres-secret
type: Opaque
data:
  POSTGRES_USER: YXVyYQ== # aura
  POSTGRES_PASSWORD: c2VjcmV0cGFzc3dvcmQ= # secretpassword
  POSTGRES_DB: YXVyYWRi # auradb
