# .github/workflows/deploy-nginx.yml
name: Deploy Nginx

on:
  push:
    branches:
      - main  # Cambia esto si usas otra rama

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Frontend
        run: |
          cd frontend
          npm install  # Instala las dependencias
          npm run build  # Construye el proyecto

      - name: Build Docker image
        run: |
          docker build -t my-nginx-app ./frontend

      - name: Push Docker image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag my-nginx-app ${{ secrets.DOCKER_USERNAME }}/my-nginx-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-nginx-app:latest
